### ISSUE TITLE
Exporting submissions gives a server error

### ISSUE THREAD

**Issue by NoelmansGlennPXL** [verbb/formie#1046]
### Describe the bug

I tried exporting a submission from Formie with the default export type but it returns a server error every single time.

### Steps to reproduce

1. Go to formie
2. Click submissions
3. Click export

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

Craft Pro 4.2.0.2

### Plugin version

2.0.4

**Comment by engram-design** [comment]
Can you provide an export of your form that you're trying to export for? There could be a number of issues, and it's likely it could be down to a field setting or combination.

Additionally, please look in your `storage/logs/formie.log` file for this error (or in your other log files in `storage/logs`) for more detail on this error. This will help us troubleshooting the issue.

We have loads of different forms and field combinations, exporting without issue.

**Comment by NoelmansGlennPXL** [comment]
This is the export of the form:

[elements.csv](https://github.com/verbb/formie/files/9308334/elements.csv)

I don't have formie.log. But I found this error in phperrors.log:

[11-Aug-2022 11:38:55 Europe/Brussels] An Error occurred while handling another error:
TypeError: array_keys(): Argument #1 ($array) must be of type array, string given in C:\Users\Glenn\OneDrive\Documents\Alpine Digital\Project CraftCMS\dataminer\vendor\craftcms\cms\src\web\CsvResponseFormatter.php:88

**Comment by engram-design** [comment]
Sorry, I did mean going to Formie > Settings > Import/Export to export the field. That just includes all the fields and settings.

This does sound similar to [another issue](https://github.com/verbb/formie/issues/966)

**Comment by NoelmansGlennPXL** [comment]
These are the contents of the form.json export as I can't paste a json file here directly: 


{
    "handle": "newtestform",
    "settings": "{\"displayFormTitle\":false,\"displayCurrentPageTitle\":false,\"displayPageTabs\":false,\"displayPageProgress\":false,\"scrollToTop\":true,\"progressPosition\":\"end\",\"defaultLabelPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"defaultInstructionsPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"submitMethod\":\"ajax\",\"submitAction\":\"message\",\"submitActionTab\":null,\"submitActionUrl\":null,\"submitActionFormHide\":false,\"submitActionMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Thank you for contacting us! Our team will get in touch shortly to follow up on your message.\\\"}]}]\",\"submitActionMessageTimeout\":null,\"submitActionMessagePosition\":\"top-form\",\"loadingIndicator\":\"spinner\",\"loadingIndicatorText\":null,\"validationOnSubmit\":true,\"validationOnFocus\":true,\"errorMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Couldn\u2019t save submission due to errors.\\\"}]}]\",\"errorMessagePosition\":\"top-form\",\"availabilityMessage\":null,\"availabilityMessageDate\":null,\"availabilityMessageSubmissions\":null,\"integrations\":[],\"submissionTitleFormat\":\"{timestamp}\",\"collectIp\":false,\"collectUser\":false,\"dataRetention\":null,\"dataRetentionValue\":null,\"fileUploadsAction\":null,\"redirectUrl\":null,\"defaultEmailTemplateId\":null,\"disableCaptchas\":false}",
    "submitActionEntryId": null,
    "requireUser": 0,
    "availability": "always",
    "availabilityFrom": null,
    "availabilityTo": null,
    "availabilitySubmissions": null,
    "defaultStatusId": 1,
    "dataRetention": "forever",
    "dataRetentionValue": null,
    "userDeletedAction": "retain",
    "fileUploadsAction": "retain",
    "fieldLayoutId": 4,
    "title": "newTestForm",
    "notifications": [
        {
            "name": "Admin Notification",
            "enabled": 1,
            "subject": "A new submission was made on \"{formName}\"",
            "recipients": "email",
            "to": "{systemEmail}",
            "toConditions": "{\"toRecipients\":[]}",
            "cc": null,
            "bcc": null,
            "replyTo": "{field.emailAddress}",
            "replyToName": null,
            "from": "{field.emailAddress}",
            "fromName": null,
            "content": "[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"A user submission has been made on the \\\"\"},{\"type\":\"variableTag\",\"attrs\":{\"label\":\"Form Name\",\"value\":\"{formName}\"}},{\"type\":\"text\",\"text\":\"\\\" form on \"},{\"type\":\"variableTag\",\"attrs\":{\"label\":\"Site Name\",\"value\":\"{siteName}\"}},{\"type\":\"text\",\"text\":\" at \"},{\"type\":\"variableTag\",\"attrs\":{\"label\":\"Timestamp (yyyy-mm-dd hh:mm:ss)\",\"value\":\"{timestamp}\"}}]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"Their submission details are:\"}]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"variableTag\",\"attrs\":{\"label\":\"All Form Fields\",\"value\":\"{allFields}\"}}]}]",
            "attachFiles": 1,
            "attachPdf": null,
            "attachAssets": null,
            "enableConditions": 0,
            "conditions": "{\"sendRule\":\"send\",\"conditionRule\":\"all\",\"conditions\":[]}"
        },
        {
            "name": "User Notification",
            "enabled": 1,
            "subject": "Thanks for contacting us!",
            "recipients": "email",
            "to": "{field.emailAddress}",
            "toConditions": "{\"toRecipients\":[]}",
            "cc": null,
            "bcc": null,
            "replyTo": null,
            "replyToName": null,
            "from": null,
            "fromName": null,
            "content": "[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"Thanks again for contacting us. Our team will get back to you as soon as we can.\"}]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"As a reminder, you submitted the following details at \"},{\"type\":\"variableTag\",\"attrs\":{\"label\":\"Timestamp (yyyy-mm-dd hh:mm:ss)\",\"value\":\"{timestamp}\"}}]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"variableTag\",\"attrs\":{\"label\":\"All Form Fields\",\"value\":\"{allFields}\"}}]}]",
            "attachFiles": 1,
            "attachPdf": null,
            "attachAssets": null,
            "enableConditions": 0,
            "conditions": "{\"sendRule\":\"send\",\"conditionRule\":\"all\",\"conditions\":[]}"
        }
    ],
    "pages": [
        {
            "settings": {
                "submitButtonLabel": "Contact us",
                "backButtonLabel": "Back",
                "showBackButton": false,
                "saveButtonLabel": "Save",
                "showSaveButton": false,
                "saveButtonStyle": "link",
                "buttonsPosition": "left",
                "cssClasses": null,
                "containerAttributes": null,
                "inputAttributes": null,
                "enableNextButtonConditions": false,
                "nextButtonConditions": [],
                "enablePageConditions": false,
                "pageConditions": [],
                "enableJsEvents": false,
                "jsGtmEventOptions": []
            },
            "userCondition": null,
            "elementCondition": null,
            "label": "Page 1",
            "rows": [
                {
                    "fields": [
                        {
                            "label": "Your Name",
                            "handle": "yourName",
                            "type": "verbb\\formie\\fields\\formfields\\Name",
                            "settings": {
                                "instructions": "Please enter your full name.",
                                "required": false,
                                "useMultipleFields": true,
                                "prefixEnabled": false,
                                "prefixCollapsed": true,
                                "prefixLabel": "Prefix",
                                "prefixPlaceholder": null,
                                "prefixDefaultValue": null,
                                "prefixPrePopulate": null,
                                "prefixRequired": false,
                                "prefixErrorMessage": null,
                                "firstNameEnabled": true,
                                "firstNameCollapsed": false,
                                "firstNameLabel": "First Name",
                                "firstNamePlaceholder": "e.g. Peter",
                                "firstNameDefaultValue": null,
                                "firstNamePrePopulate": null,
                                "firstNameRequired": true,
                                "firstNameErrorMessage": null,
                                "middleNameEnabled": false,
                                "middleNameCollapsed": true,
                                "middleNameLabel": "Middle Name",
                                "middleNamePlaceholder": null,
                                "middleNameDefaultValue": null,
                                "middleNamePrePopulate": null,
                                "middleNameRequired": false,
                                "middleNameErrorMessage": null,
                                "lastNameEnabled": true,
                                "lastNameCollapsed": false,
                                "lastNameLabel": "Last Name",
                                "lastNamePlaceholder": "e.g. Sherman",
                                "lastNameDefaultValue": null,
                                "lastNamePrePopulate": null,
                                "lastNameRequired": true,
                                "lastNameErrorMessage": null,
                                "subfieldLabelPosition": null,
                                "matchField": null,
                                "placeholder": "Your name",
                                "defaultValue": null,
                                "prePopulate": null,
                                "errorMessage": null,
                                "labelPosition": "verbb\\formie\\positions\\Hidden",
                                "instructionsPosition": "verbb\\formie\\positions\\AboveInput",
                                "cssClasses": null,
                                "containerAttributes": null,
                                "inputAttributes": null,
                                "includeInEmail": true,
                                "enableConditions": false,
                                "conditions": {
                                    "showRule": "show",
                                    "conditionRule": "all",
                                    "conditions": []
                                },
                                "enableContentEncryption": false,
                                "visibility": null,
                                "isNested": false
                            }
                        }
                    ]
                },
                {
                    "fields": [
                        {
                            "label": "test upload",
                            "handle": "testUpload",
                            "type": "verbb\\formie\\fields\\formfields\\FileUpload",
                            "settings": {
                                "instructions": null,
                                "required": false,
                                "searchable": true,
                                "sizeLimit": null,
                                "sizeMinLimit": null,
                                "limitFiles": null,
                                "restrictFiles": true,
                                "allowedKinds": [
                                    "image",
                                    "pdf"
                                ],
                                "uploadLocationSource": "volume:a5126da8-39f7-4736-8afb-4eed6f28c39b",
                                "uploadLocationSubpath": "upload",
                                "restrictLocation": true,
                                "restrictedLocationSource": "volume:a5126da8-39f7-4736-8afb-4eed6f28c39b",
                                "restrictedLocationSubpath": "upload",
                                "allowSubfolders": false,
                                "restrictedDefaultUploadSubpath": null,
                                "defaultUploadLocationSource": null,
                                "defaultUploadLocationSubpath": null,
                                "allowUploads": true,
                                "showUnpermittedVolumes": false,
                                "showUnpermittedFiles": false,
                                "previewMode": "full",
                                "matchField": null,
                                "placeholder": null,
                                "defaultValue": null,
                                "prePopulate": null,
                                "errorMessage": null,
                                "labelPosition": null,
                                "instructionsPosition": null,
                                "cssClasses": null,
                                "containerAttributes": null,
                                "inputAttributes": null,
                                "includeInEmail": true,
                                "enableConditions": false,
                                "conditions": null,
                                "enableContentEncryption": false,
                                "visibility": null,
                                "isNested": false,
                                "limitOptions": null,
                                "displayType": "dropdown",
                                "labelSource": "title",
                                "orderBy": "title ASC",
                                "multiple": false,
                                "allowSelfRelations": false,
                                "localizeRelations": false,
                                "maxRelations": null,
                                "minRelations": null,
                                "selectionLabel": null,
                                "showSiteMenu": false,
                                "source": null,
                                "sources": "*",
                                "targetSiteId": null,
                                "validateRelatedElements": false,
                                "viewMode": null
                            }
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by engram-design** [comment]
Thanks for this, although I can't seem to replicate this with submissions on my end. 

Is there a stack trace error in your `phperrors.log` log file with more info? 

If you can open up the Network tab in your Chrome dev tools (or similar for another browser), there should be a network item with an error. Can you look at the "Preview" tab to see what the error being reported is?

![image](https://user-images.githubusercontent.com/1221575/184329278-95de676a-e8b0-459d-be50-2eb330e132cd.png)

**Comment by NoelmansGlennPXL** [comment]
Dev tools: 
![image](https://user-images.githubusercontent.com/74272244/184331404-6dfff323-1795-4a50-ab5a-c17a0c228af9.png)

stack trace in phperrors.log:
![image](https://user-images.githubusercontent.com/74272244/184331606-62337f8b-e6a0-46c0-9906-84605af67cae.png)

**Comment by engram-design** [comment]
Your dev tools screenshot isn't showing the preview for the error (its the one above you're highlighting looks like), but regardless the error log does give some useful info.

I've added a fix for this if you'd like to test it. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.6](https://github.com/verbb/formie/releases/tag/2.0.6)

**Comment by ITh1erry** [comment]
Changed my verbb/formie requirement in composer.json to 2.0.6, removed my vendor and composer.lock, ran composer update but the problem still persists. Still experiencing the same error:
![image](https://user-images.githubusercontent.com/56435910/186098260-038f56b5-0d1c-4bfd-8bf2-4f2d465cce96.png)

**Comment by engram-design** [comment]
Are you able to send your database to `support at verbb.io` for us to look at? I cannot reproduce your issue with your field setup, so it may be down to your content in your fields that's stored differently to what I can replicate.

**Comment by ITh1erry** [comment]
I've just sent a message to support at verbb.io with an export of my database, hopefully this could pinpoint the issue.

Thanks in advance!

**Comment by engram-design** [comment]
Thanks for your information, that's certainly helped. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.7",
  "...": "..."
}
```

Then run `composer update`.

**Comment by ITh1erry** [comment]
Thank you very much, this did the trick indeed! Very much appreciated!
