### ISSUE TITLE
Cannot resave submissions from the CLI

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#1066]
### Describe the bug

When trying to resave all submissions from the CLI, the following error is thrown:

```
Exception 'Error' with message 'Class "O:40:"verbb\formie\elements\db\SubmissionQuery":85:{s:2:"id";N;s:6:"siteId";s:1:"*";s:6:"formId";s:4:"6374";s:8:"statusId";N;s:6:"userId";N;s:12:"isIncomplete";b:0;s:6:"isSpam";b:0;s:17:"" not found'

in /var/www/html/vendor/craftcms/cms/src/console/controllers/ResaveController.php:328

Stack trace:
#0 /var/www/html/vendor/verbb/formie/src/Formie.php(585): craft\console\controllers\ResaveController->resaveElements('O:40:"verbb\\for...')
#1 [internal function]: verbb\formie\Formie->verbb\formie\{closure}()
#2 /var/www/html/vendor/craftcms/cms/src/console/CallableAction.php(43): call_user_func_array(Object(Closure), Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): craft\console\CallableAction->runWithParams(Array)
#4 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('formie-submissi...', Array)
#5 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(224): yii\console\Controller->runAction('formie-submissi...', Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('formie-submissi...', Array)
#7 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('resave/formie-s...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('resave/formie-s...', Array)
#9 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('resave/formie-s...', Array)
#10 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#12 /var/www/html/craft(13): yii\base\Application->run()
#13 {main}
Failed to execute command php craft resave/formie-submissions: exit status 1
```

Every existing submission can be edited and saved via the CP, not a single one is throwing an error so this is specific to resaving via the CLI (had an error when saving via the CP previously but cannot replicate it). I can try to start clean to test this and pinpoint the issue more precisely if you need. Will try to find some time to do that and report back.

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.8

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
So, I still have issues with resaving:

First, resaving ends with an error although submissions look like they have been processed.

```
sierraromeo@Jean-Lucs-MacBook-Pro generationopera % ddev exec php craft resave/formie-submissions
Resaving 36 elements ...
    - [1/36] Resaving Ma Yichen (9792) ... done
    - [2/36] Resaving Vinson-Peloso Roxane (9776) ... done
    - [3/36] Resaving LEFORT Jeanne (9772) ... done
    - [4/36] Resaving BackèsCorentin -  (9692) ... done
    - [5/36] Resaving DefontenayAnouk -  (9675) ... done
    - [6/36] Resaving TattiAmélie -  (9668) ... done
    - [7/36] Resaving 2022-08-24 10:58:08 (9620) ... done
    - [8/36] Resaving 2022-08-21 16:35:20 (9567) ... done
    - [9/36] Resaving 2022-08-21 15:05:49 (9560) ... done
    - [10/36] Resaving Leterme Louise (9462) ... done
    - [11/36] Resaving 2022-08-17 19:53:39 (9380) ... done
    - [12/36] Resaving 2022-08-16 22:33:48 (9349) ... done
    - [13/36] Resaving 2022-08-15 22:29:51 (9315) ... done
    - [14/36] Resaving 2022-08-15 11:21:24 (9301) ... done
    - [15/36] Resaving 2022-08-13 11:32:20 (9247) ... done
    - [16/36] Resaving 2022-07-29 12:52:11 (8860) ... done
    - [17/36] Resaving 2022-07-27 13:50:42 (8778) ... done
    - [18/36] Resaving 2022-07-20 12:35:05 (8518) ... done
    - [19/36] Resaving 2022-07-20 12:30:33 (8474) ... done
    - [20/36] Resaving 2022-07-18 23:31:34 (8446) ... done
    - [21/36] Resaving 2022-07-17 13:56:38 (8384) ... done
    - [22/36] Resaving 2022-07-16 11:19:14 (8356) ... done
    - [23/36] Resaving 2022-07-16 01:41:00 (8313) ... done
    - [24/36] Resaving 2022-07-12 15:30:36 (8284) ... done
    - [25/36] Resaving 2022-07-12 13:11:34 (8272) ... done
    - [26/36] Resaving 2022-07-08 19:27:51 (8174) ... done
    - [27/36] Resaving 2022-07-06 13:48:24 (8028) ... done
    - [28/36] Resaving 2022-07-03 08:34:55 (7666) ... done
    - [29/36] Resaving 2022-07-01 18:20:13 (7646) ... done
    - [30/36] Resaving 2022-06-24 01:17:22 (7111) ... done
    - [31/36] Resaving 2022-06-23 22:05:50 (7098) ... done
    - [32/36] Resaving 2022-06-22 11:39:37 (7035) ... done
    - [33/36] Resaving 2022-06-20 15:02:15 (6988) ... done
    - [34/36] Resaving 2022-06-03 14:25:56 (6601) ... done
    - [35/36] Resaving 2022-06-03 13:44:11 (6589) ... done
    - [36/36] Resaving 2022-06-07 16:22:58 (6548) ... done
Done resaving elements.

Resaving 2 elements ...
    - [1/2] Resaving 2022-08-27 11:19:15 (9689) ... done
    - [2/2] Resaving 2022-07-13 14:52:33 (8303) ... done
Done resaving elements.

Failed to execute command php craft resave/formie-submissions: exit status 1
```

Second, submissions title are not updated by default with the value of the form's `Submission Title Format` setting. So I guess we have to use the --set / --to flags to update the title which brings me this question: In a nested field (Name, Address), how do I refer to the field name, let's say first name for instance?

Take the following example, I want the title to be `LastName FirstName`. I use the Name field with the handle `fullName`. How can I update the title field? 

`resave/formie-submissions --set title --to "={lastNameField ~ ' ' ~ firstNameField}"`

Third and not related to this issue per se but to a submission's title, shouldn't it be handled like a slug (it's even located in the same spot)? What I mean is that clearing the title of the submission would not throw an empty field error but regenerate the title according to the title setting?

**Comment by engram-design** [comment]
Not sure what that error is. Can you check in your log files for `[error]` for more info?

So we are relying on Craft's own [element-resaving controller](https://github.com/craftcms/cms/blob/ac616d429ee369b83478b3e8441ed5d6693f9036/src/console/controllers/ResaveController.php#L319) which does act a little differently to a general save. But the title is always there as a default when created. It isn't updated each time, and forced to adhere to the format.

A title is always overridable, and doesn't act like a slug. I think this is a nice feature in case you **do** want to rename submissions to something else, but it's auto-generated from the Submission Title Format. Besides, changing this now would be a breaking change, so not keen to change this on a whim.

And you can use sub-field notation.

```
resave/formie-submissions --set=title --to="={fullName.lastName} {fullName.firstName}"
```

**Comment by JeanLucEsser** [comment]
Ok so for the error (no logs associated), I tried running the command from inside my ddev container and the error is gone. So it errors out only when running through ddev `ddev exec php craft resave/...`. I ran into other issues related to resaving entries via ddev today so I guess it's safe to consider the issue resolved as far as you are concerned.

I was comparing the submission title to the slug precisely because it is auto generated, hence the idea of being able to clear the field and let it regenerate from saving. Imagine that the format for the title is `lastName firstName`. If there's a typo in the name, you have to change it in both places (lastName field and title field). Could be easier to be able to just clear the title field and let it be regenerated on save if needed. This is not actually an issue though, just a thought ;)

**Comment by JeanLucEsser** [comment]
Bonus question, how would you access the submission's form properties from within the submission, let's say I want to use the form's handle in my title format.

**Comment by JeanLucEsser** [comment]
> I ran into other issues related to resaving entries via ddev today so I guess it's safe to consider the issue resolved as far as you are concerned.

So regarding ddev, I found what the problem was, see this [discord message](https://discord.com/channels/456442477667418113/456442477667418115/1015338041029689385).

Using `ddev php craft ...` makes everything work as it should, error message is gone for good!

**Comment by engram-design** [comment]
Yep, understand the thinking there with title being enforced. I'll give it some thought, but a change won't be introduced soon that'll be breaking for people who might be reliant on being able to edit the title. Good thinking though.

To access attributes, that's just `{id}`, `{title}`, `{dateCreated}` etc.

Glad you got the command sorted!

**Comment by engram-design** [comment]
Fixed in [2.0.9](https://github.com/verbb/formie/releases/tag/2.0.9)
