### ISSUE TITLE
Fails to send Zapier webhook when form contains an `Entries` field with many items

### ISSUE THREAD

**Issue by cmalven** [verbb/formie#1069]
### Describe the bug

When a Formie form has an `Entries` field and the entries field has many elements, Formie will run out of memory when trying to send to webhook to Zapier.

This happens either when clicking `Send Test Payload` in the form settings, or when submitting the form on the frontend.

If sent on the frontend, the issue will only appear if the Entries field has a selected value. If it doesn't have a value, the webhook seems to send as expected. If triggered using `Send Test Payload` the webhook will always fail to send - probably because it always includes a value for the field.

The only message for this error appears in `logs/phperrors.log` and simply says that the `Allowed memory size of XXXXX byes exhausted`.

Otherwise the form submits just fine - it is only the Zapier hooks that fail to send. I've tested Zapier webhooks with other forms on the same site that do not have an Entires field and the webhooks are sent as expected.

I'm not exactly sure whether the issue is the type of entries being requested (e.g. their field complexity), the number of entries related to the allowed entries, or some other issue related to those elements, but I do know that some types of entries will trigger the issue and some won't.

### Steps to reproduce

1. Create a form with an `Entries` field that has many elements and a Zapier integration connected
2. Attempt to send a Zapier webhook either via `Send Test Payload` in the form settings or by submitting the form on the frontend with the entries field set to a value
3. If sent on the frontend, the queued task will hang indefinitely
4. If sent using `Send Test Payload` PHP will run out of memory and an error will be displayed

### Form settings

- Multi-page form: No
- Submission Method: Either Ajax or Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.53.1

### Plugin version

1.6.10

### Multi-site?

Yes

### Additional context

Tested using Laravel Valet with a PHP Memory Limit of 512

**Comment by engram-design** [comment]
This is probably down to the serialization of the entry (or any other element for that matter).

Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by cmalven** [comment]
Thanks @engram-design. I just re-install Formie using `dev-craft-3` and I'm still having the same issue. No change in behavior.

**Comment by cmalven** [comment]
@engram-design Thank you! This does seem to have resolved things. Thank you for your quick response to this.

**Comment by engram-design** [comment]
Fixed in [1.6.11](https://github.com/verbb/formie/releases/tag/1.6.11)
