### ISSUE TITLE
Trying to preview an email notification in a stencil gives error

### ISSUE THREAD

**Issue by HannahDeWachter** [verbb/formie#1122]
### Describe the bug

I get following error message when trying to preview an email notification on a Stencil: `verbb\formie\elements\Submission::setForm(): Argument #1 ($form) must be of type verbb\formie\elements\Form, null given, called in /vendor/verbb/formie/src/controllers/EmailController.php on line 118`

![Screenshot 2022-10-13 at 13 36 25](https://user-images.githubusercontent.com/55497252/195586993-0e339ea1-7271-4ba8-980c-cbbe217662dc.png)

### Steps to reproduce

1. Open an existing Stencil 
2. Open a email notification and go to preview

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes

### Craft CMS version

4.2.5.1

### Plugin version

2.0.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.12",
  "...": "..."
}
```

Then run `composer update`.

**Comment by HannahDeWachter** [comment]
hi @engram-design,
This still doesn't work. I changed my composer.json file to require `"verbb/formie": "dev-craft-4 as 2.0.12",` and ran `composer update`, but I still get the same error.

**Comment by engram-design** [comment]
@HannahDeWachter My apologies, it looks like this commit didn't push up correctly. Running `composer update` now should do the trick.

**Comment by HannahDeWachter** [comment]
@engram-design Thank you! This solved this error.

**Comment by engram-design** [comment]
Fixed in [2.0.13](https://github.com/verbb/formie/releases/tag/2.0.13)
