### ISSUE TITLE
Saving Date fields to entries results in timezone mismatch

### ISSUE THREAD

**Issue by jorisnoo** [verbb/formie#1169]
### Describe the bug

I've built a form that makes use of Date/Time fields and then stores the submissions as entries (using the 'Save as Entry' integration). The Formie Date/Time fields are mapped to Craft Date/Time fields.

However, I'm experiencing the following issue:
* The submitted time is stored correctly (the same as it was entered in the form by the user) in the database, eg. 16:00
* Is is displayed correctly as 16:00 in the submission
* The submission is saved to a new (craft) entry
* The time in the craft entry, however, is now stored as 17:00 in the `content` table
* This leads to it being displayed as 18:00 when rendering the entry (as the timezone of Craft is set to UTC+1)

Even when changing the timezone in Craft (eg. to UTC+3), a submission of 16:00 was still saved as 17:00 in the corresponding entry in the `content` table.

In order for the time to be reflected correctly in the entry, it should be stored as UTC; so that date/times submitted through a form and then saved in entries still are displayed the same.

Would there be a way to achieve this or am i missing something obvious?
Thank you very much for any help!

### Steps to reproduce

1. Set the timezone of Craft to UTC+1
1. Create a form with a Date/Time field
2. Enable the 'Save as Entry' integration and map the Date/Time field to a Date field
3. Submit the form through the frontend
4. View the newly created entry in craft

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.1

### Plugin version

2.0.17

### Multi-site?

Yes

**Comment by engram-design** [comment]
For starters, we don't store values for Formie date/time fields as UTC, because we would need to also store the original timezone information, which seems unnecessary. In fact we don't _want_ to manipulate date/time values when it comes to Formie, and it should always reflect **exactly** the date/time the user has inputted.

Otherwise, depending on the timezone set at the Craft level, the date/time values change, which no longer reflects the correct value as per the user's provided value. While Craft dates are stored as UTC, they're converted to be shown as the Craft system time.

However, this is an interesting case, where mapping to native Craft date/time fields, through a submission are incorrect. We now assume that the date set is in the system timezone, which when converted as saved to the database correctly as UTC, will convert back to the correct timezone (according to your Craft system timezone settings).

Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.17",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jorisnoo** [comment]
@engram-design You're amazing. This was exactly the issue i was encountering — which seems to be perfectly solved with this update. Thank you!

**Comment by frankkepler** [comment]
@engram-design I was also having an issue in the Craft 3 version, where dates were being saved and passed along through user integration, the user would end up with a date that was 1 day previous than the date they entered. 

**Your changes here when implemented on the Craft 3 version solve my issue.**

As always, thanks for everything.

**Comment by engram-design** [comment]
Fixed in [2.0.18](https://github.com/verbb/formie/releases/tag/2.0.18) and [1.6.19](https://github.com/verbb/formie/releases/tag/1.6.19)

**Comment by jorisnoo** [comment]
Dear @engram-design, there unfortunately still appears to be an offset when saving submissions as entries, at least in my case:

A submission of "8:00" is now (since the update) stored as "8:00" in both the submission and the craft entry in the database. However, since my craft installation is set to UTC+1, is is displayed as "9:00" in the craft entry. I assume that it would work as long as the craft timezone is set to UTC.

What I would actually need is the "save as entry" integration to convert the entered date _from_ the craft timezone _to_ UTC: eg. "8:00" should be stored as "7:00" to the `content` table if the timezone is set to UTC+1, in order for craft to correctly display it as "8:00" again. Are you able to reproduce this — and does this make sense?

As always, thanks a lot for all your effort!

**Comment by engram-design** [comment]
Hmmm, yeah I suppose you're right in that case. To reiterate, we don't want to store time in UTC because we would also need to store the timezone for the date. It's far simpler to just save the date/time as-is. Secondly, we also want to tell Craft not to adjust the date/time to the timezone defined in the control panel.

All that is totally fine for Formie, its fields, submissions, etc. But if you have an element integration where it passes the form value off to an entry or other element, that indeed is an issue. Hence a value entered as 8:00 in your form will be stored as 8:00 UTC in the database. Craft will then convert that to whatever the timezone the current user in the control panel is using.

Last I checked, this _was_ still working in the correct manner.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.22"`

**Comment by engram-design** [comment]
Updated in [2.0.23](https://github.com/verbb/formie/releases/tag/2.0.23)

**Comment by jorisnoo** [comment]
I just tested this and it is now working as expected. Thank you! 🙏
