### ISSUE TITLE
Custom error message on required field not rendering when using themeConfig + resetting all classes

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/formie#1193]
### Describe the bug

When setting a custom error message on required fields the error message does not get rendered when using the new themeConfig together with resetClasses.

The error message does get populated to the data-fui-message attribute but when you validate the form the default 'Please fill out this field.' is used.

This bug occurred before but was fixed in 2.0.5, see #1040

Additional info:

When setting a custom error message for a required Email field the custom error message shows up if you type an invalid email, when the field is empty the default 'Please fill out this field.' shows like the other fields.

### Steps to reproduce

1. Set a custom error message on a required field.
2. Use the ready-made tailwind themeConfig
3. Validate the form

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes

### Craft CMS version

4.3.3

### Plugin version

2.0.18

### Multi-site?

No

**Comment by engram-design** [comment]
Sorry about that. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.19](https://github.com/verbb/formie/releases/tag/2.0.19)

**Comment by robin-braibant-alpine** [comment]
@engram-design Currently running the 2.0.20 version of Formie and this issue still occurs on the agree field:
<img width="1514" alt="Screenshot 2023-01-18 at 14 50 40" src="https://user-images.githubusercontent.com/117266131/213188749-f37b9b36-4769-437a-9ebd-a7463094b2a6.png">

**Comment by engram-design** [comment]
Slightly unrelated issue due to their incorrect placements. Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [2.0.21](https://github.com/verbb/formie/releases/tag/2.0.21)

**Comment by KatieMFritz** [comment]
I'm getting this same bug using the `dev-craft-4` version.

Edit: I had these settings in my themeConfig. Removing them made it work.
```
	fieldContainer: false,
	fieldInputContainer: false,
```

**Comment by engram-design** [comment]
That would make sense @KatieMFritz particularly removing `fieldContainer` which is the most important one of all. That element is essentially the "top level" for a field, and is how we can figure out where to place errors for different field types, and lots more. As such, removing it from render - while possible - is somewhat of an advanced move.
