### ISSUE TITLE
[Integration]: Unable to set Opt-In Field for Campaign Integration

### ISSUE THREAD

**Issue by jorisnoo** [verbb/formie#1270]
### Describe the bug

I'm trying to set an 'agree' field as the Opt-In field for the Campaign Integration. When re-saving the form, however, the setting is reverted to 'Always Opt-in'.

### Steps to reproduce

1. Create a new form with an agree field
2. Enable the Integration for the installed Campaign Plugin https://putyourlightson.com/plugins/campaign
3. In the form settings, enable the integration and select the agree field of the form as the Opt-In Field
4. Save and reload the settings

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.6.1 

### Plugin version

2.0.21

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.21",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jorisnoo** [comment]
Thank you, @engram-design !

**Comment by engram-design** [comment]
Fixed in [2.0.22](https://github.com/verbb/formie/releases/tag/2.0.22)

**Comment by jorisnoo** [comment]
@engram-design Thanks a lot for fixing this — the field is now properly persisted.
It appears, however, that the functionality is still broken; even though an 'agree' field is selected, the integration works as if set to 'always opt-in'.
Thank you for having another look at this 🙏

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)
