### ISSUE TITLE
Unable to mark spam as "not spam"

### ISSUE THREAD

**Issue by amphibian** [verbb/formie#1286]
### Describe the bug

A client found that submissions were going to spam. I looked and found many form submissions in the spam queue erroneously. But I am unable to get them out!

### Steps to reproduce

1. Using the bulk checkbox action on one or more of the spam submissions results in the message "**Could not update spam state due to validation errors.**".
2. Opening an individual spam submission and toggling the "spam" toggle off, then saving, results in a Craft error: **Request has invalid param submitAction**.

As a result I am unable to get any of these spam submissions out of the queue.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.61

### Plugin version

dev-craft-4

### Multi-site?

No

**Comment by engram-design** [comment]
I see you're on `dev-craft-4`, but when was the last time you updated to the latest branch code (run `composer update`)?

I only ask because there was a similar issue that was fixed in [2.0.21](https://github.com/verbb/formie/blob/craft-4/CHANGELOG.md#2021---2023-01-30) and you should only be using `dev-craft-4` for temp fixes and move back to a proper release tag (just in case you moved to this a while ago).

**Comment by amphibian** [comment]
Thanks Josh - switching to the current, non-dev branch fixed the issue of saving an individual submission as "not spam."

I'm still unable to save multiple at once with the bulk action (same error message - "Could not update spam state due to validation errors."), but at least I have a way to get these out of spam now!

**Comment by engram-design** [comment]
Hmm, I can't seem to replicate that, sorry. It could very well be down to your field setup though. If you're able to, if you can send a support requests for your form through to `support@verbb.io` I can see if I can replicate that.

**Comment by engram-design** [comment]
Updated in [2.0.23](https://github.com/verbb/formie/releases/tag/2.0.23)
