### ISSUE TITLE
Importing submissions with FeedMe imports the first submission (all others marked as an existing element)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1295]
### Describe the bug

I'm trying import a data set as submissions for a form through FeedMe and the Submission element type, but hitting a weird issue.

I'm using just the create new elements strategy and it seems after the first submission (there's a total 345), FeedMe thinks everything else is a duplicate as per the logs it references the element ID of the first submission that did get created.

Basically the log is full of this after the first row:

```
{"date":"2023-02-11 15:29:55","type":"info","message":"Feed name: Existing element [`#795829`](http:\/\/example.ddev.site\/manage\/formie\/submissions\/formHandle\/795829) found.","key":"tvpchaxypioteoesphux"}
{"date":"2023-02-11 15:29:55","type":"info","message":"Feed name: Skipped due to an existing element found, and elements are set to add only.","key":"tvpchaxypioteoesphux"}
```

The element ID `795829` is the first submission that was created. I have tried with both CSV and JSON but they both trigger the same issue. Not sure why it thinks everything after the first element already exists, I guess because only a single element ID is used?

Setting the Create/Update strategy, basically all 345 rows are looped through but each row will overwrite the previous under a single element ID.

### Steps to reproduce

1. Create a FeedMe feed using the submission element type with the create strategy.
2. Use Title as the unique key. The title value in the data is `[uniqueid] - [First Name] [Last Name]` 
3. Attempt to import feed items as submissions
4. Only the first submission is imported, the rest are all marked as existing.

### Form settings

N/A

### Craft CMS version

3.7.65.2

### Plugin version

1.6.22

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.23",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Thank you. I thought I was going crazy!

**Comment by jamesmacwhite** [comment]
Sorry! The same behaviour is still happening after setting to `dev-craft-3`. Only one element is imported with create only set.

There's also an error with hidden fields, but I can change those to just plain text if needed.

The log error is different, no longer mentions the one element ID anymore.

```
{"date":"2023-02-12 00:30:30","type":"info","message":"FeedMe feed: Match existing element with data `{\"title\":\"8788224769 - Example Name\"}`.","key":"qvlwkqiqaxzyhlwqnkqv"}
{"date":"2023-02-12 00:30:31","type":"error","message":"FeedMe feed: `Call to a member function setFieldValue() on null - Hidden.php: 143`.","key":"qvlwkqiqaxzyhlwqnkqv"}
{"date":"2023-02-12 00:30:31","type":"info","message":"FeedMe feed: Starting processing of node `#2`.","key":"kwsfbcxrbnstsizvlmob"}
{"date":"2023-02-12 00:30:31","type":"info","message":"FeedMe feed: Match existing element with data `{\"title\":\"8794982969 - Another Example\"}`.","key":"kwsfbcxrbnstsizvlmob"}
{"date":"2023-02-12 00:30:31","type":"error","message":"FeedMe feed: `Call to a member function setFieldValue() on null - Hidden.php: 143`.","key":"kwsfbcxrbnstsizvlmob"}
{"date":"2023-02-12 00:30:31","type":"info","message":"FeedMe feed: Starting processing of node `#3`.","key":"jjywufdizdvyiixqtjow"}
{"date":"2023-02-12 00:30:31","type":"info","message":"FeedMe feed: Match existing element with data `{\"title\":\"8826490799 - Something else\"}`.","key":"jjywufdizdvyiixqtjow"}
{"date":"2023-02-12 00:30:31","type":"error","message":"FeedMe feed:: `Call to a member function setFieldValue() on null - Hidden.php: 143`.","key":"jjywufdizdvyiixqtjow"}
```

**Comment by engram-design** [comment]
Yeah, they're importing for me all correctly, strange.

```json
[
    {
        "title": "IMPORTED 1",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    },
    {
        "title": "IMPORTED 2",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    },
    {
        "title": "IMPORTED 3",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    }
]
```

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/1221575/218287122-a252eab4-afdc-4ce0-8c37-6c7c10b04f76.png">

**Comment by jamesmacwhite** [comment]
Sorry! I think the hidden field error was causing more issues behind the scenes than logged. Changing to plain text and re-running seems to resolve those issues, but I think there's still an issue with the matching, as I just have create only set and re-running twice it duplicated all the submissions again when title was set, with the value `[unique key] - [First Name] [Last Name]`

**Comment by engram-design** [comment]
Should be fixed in `dev-craft-3`.

**Comment by jamesmacwhite** [comment]
Confirmed, retested with all data imported and now it doesn't reimport the same data again with the adjustment in the query.

**Comment by engram-design** [comment]
Updated in [1.6.24](https://github.com/verbb/formie/releases/tag/1.6.24)
