### ISSUE TITLE
Submission import through FeedMe. Several field types do not import data

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1296]
### Describe the bug

When attempting to import data through Feed Me via the submissions element type the following fields did not import data:

* Email address (Email type)
* Single line text
* Multi line text
* Date/time field
* Hidden field

It might be due to the fact that within: https://github.com/verbb/formie/tree/craft-3/src/templates/integrations/feedme/fields, only those fields listed in the fields folder are handled.

Both name and phone data did have their data imported.

### Steps to reproduce

1. Configure a Feed Me feed using the Submission element type for a form
2. Map any of the listed fields mentioned above
3. Run the feed
4. Observe no data is imported for the fields which are not handled

### Form settings

N/A

### Craft CMS version

3.7.65.2

### Plugin version

1.6.22

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.23",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
Thanks. I'll give the import another test with the different field types.

**Comment by jamesmacwhite** [comment]
Sorry, still broken on dev-craft-3 I'm afraid, none of the fields populated any data, besides the name and phone field.

**Comment by engram-design** [comment]
Strange, they seem to be populating for me.

```json
[
    {
        "title": "IMPORTED 1",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    },
    {
        "title": "IMPORTED 2",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    },
    {
        "title": "IMPORTED 3",
        "firstName": "Josh",
        "lastName": "Crawford",
        "email": "test@test.com",
        "message": "test"
    }
]
```

<img width="803" alt="image" src="https://user-images.githubusercontent.com/1221575/218287102-cc36ff64-4b91-49c9-b746-dfa439b52ed1.png">

**Comment by jamesmacwhite** [comment]
Sorry about that, to confusing things I think the error with the hidden field was the issue there. I've now removed it and converted to plain text and re-run which now allows to populate.

However, I think there's still an issue with the general matching as with create only and re-running it duplicated all the submissions again when title with the unique value is set.

**Comment by jamesmacwhite** [comment]
I'll confirm field types mentioned originally now work. Hidden fields are best avoided based on the error in the logs by the looks of it.

The matching issue, I'll discuss on: https://github.com/verbb/formie/issues/1295

**Comment by engram-design** [comment]
The hidden field error is fixed in `dev-craft-3`.

**Comment by engram-design** [comment]
Updated in [1.6.24](https://github.com/verbb/formie/releases/tag/1.6.24)
