### ISSUE TITLE
ActiveCampaign: API exception when tags already exists

### ISSUE THREAD

**Issue by martinleveille** [verbb/formie#1389]
### Describe the bug

When you have more than 20 tags in your ActiveCampaign, the plugin did not get paginated results when it fetched all the tags. Only the first 20 are returned.

Then the plugin tries to create tags that already exist and the ActiveCampaign API throws an exception.

Pull request that fix this issue #1388 

### Steps to reproduce

1. Have an ActiveCampaign with more that 20 tags.
2. Enable the ActiveCampaign integration on your form.
3. Assign an Hidden field with tags separated by comma.
4. Try using tags after the first pagination, like the 25th for example.
5. Receive an exception from the ActiveCampaign API.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.4.6.1

### Plugin version

2.0.26

### Multi-site?

Yes

### Additional context

```
{
    "name": "Exception",
    "message": "API error: “{\"message\":\"Could not process request\",\"error\":\"Duplicate entry 'contact-TEST' for key 'typetag'\"}” /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113",
    "code": 0,
    "error": "API error: “{\"message\":\"Could not process request\",\"error\":\"Duplicate entry 'contact-TEST' for key 'typetag'\"}” /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113",
    "exception": "verbb\\formie\\errors\\IntegrationException",
    "file": "/var/www/html/vendor/verbb/formie/src/base/Integration.php",
    "line": 136,
    "trace": [
        {
            "file": "/var/www/html/vendor/verbb/formie/src/integrations/emailmarketing/ActiveCampaign.php",
            "line": 213,
            "function": "apiError",
            "class": "verbb\\formie\\base\\Integration",
            "type": "::"
        },
        {
            "file": "/var/www/html/vendor/verbb/formie/src/services/Submissions.php",
            "line": 283,
            "function": "sendPayload",
            "class": "verbb\\formie\\integrations\\emailmarketing\\ActiveCampaign",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/verbb/formie/src/controllers/SubmissionsController.php",
            "line": 935,
            "function": "sendIntegrationPayload",
            "class": "verbb\\formie\\services\\Submissions",
            "type": "->"
        },
        {
            "function": "actionRunIntegration",
            "class": "verbb\\formie\\controllers\\SubmissionsController",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php",
            "line": 57,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Controller.php",
            "line": 178,
            "function": "runWithParams",
            "class": "yii\\base\\InlineAction",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Module.php",
            "line": 552,
            "function": "runAction",
            "class": "yii\\base\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
            "line": 302,
            "function": "runAction",
            "class": "yii\\base\\Module",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
            "line": 627,
            "function": "runAction",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
            "line": 281,
            "function": "_processActionRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Application.php",
            "line": 384,
            "function": "handleRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/web/index.php",
            "line": 12,
            "function": "run",
            "class": "yii\\base\\Application",
            "type": "->"
        }
    ]
}
```

**Comment by engram-design** [comment]
Appreciate the PR! Updated for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.26"`

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/formie/releases/tag/2.0.27)

**Comment by jimirobaer** [comment]
This issue is still present on Formie 1.6.26. I made a small pull request here to add the necessary function that fixes this issue: https://github.com/verbb/formie/pull/1449.
