### ISSUE TITLE
Create form from "contact form" stencil: admin notification from e-mail

### ISSUE THREAD

**Issue by bartdigitalpulse** [verbb/formie#1492]
### Describe the bug

When you create a new form using the default stencil "contact form" the Email notification "Admin Notification" has the "From Email" set as "E-mail address". This is the e-mail of the person who filled in the form. As far as I know you can't use a random e-mail as the sender. I would be better to just leave it empty.

For smaller projects this stencil is sometimes used and we noticed this just now.

### Steps to reproduce

1. Create new form
2. Select "contact form" stencil
3. Fill in form with random email
4. E-mail is not received by admin because mail server is not allowed to use this e-mail as sender

### Form settings

not applicable

### Craft CMS version

Craft Solo 4.4.15

### Plugin version

2.0.32

### Multi-site?

Yes

**Comment by engram-design** [comment]
Excellent point and you're correct. In fact, it's one of our common [troubleshooting](https://verbb.io/craft-plugins/formie/user-guides/how-to-keep-email-notifications-out-of-your-junk-emails) steps to _not_ do this. The users' email should instead only be used for the "Reply To" value, which doesn't affect email sending deliverability.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.32"`.

**Comment by engram-design** [comment]
Fixed in [2.0.33](https://github.com/verbb/formie/releases/tag/2.0.33)

**Comment by bartdigitalpulse** [comment]
Thanks! Can this fix also be added to Craft 3 versions? I just tested this on Formie version 1.6.34 an it's still present. Still a lot of clients on Craft 3 and some create their new forms from the template. @engram-design

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.34"`.

**Comment by engram-design** [comment]
Fixed in [1.6.35](https://github.com/verbb/formie/releases/tag/1.6.35)
