### ISSUE TITLE
Repeater subfield available in conditions after adding

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#1528]
### Describe the bug

Repeater subfields are initially available in condition builders after being added to a repeater but before saving.

### Steps to reproduce

1. Add a field to a repeater.
2. Add another field to the same repeater, then in the Conditions tab, create a rule and select the previously created field along with a condition and value.
3. Apply the changes, then save the form.
4. After save, click on the second field and view the Conditions tab. The Field setting is blank and the first field is no longer available as an option.

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.4.16.1

### Plugin version

2.0.33

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.34.1"`.

**Comment by engram-design** [comment]
Fixed in [2.0.35](https://github.com/verbb/formie/releases/tag/2.0.35)

**Comment by mark-chief** [comment]
Eeekk.. any chance of getting this for Craft 3?

**Comment by mark-chief** [comment]
> Fixed in [2.0.35](https://github.com/verbb/formie/releases/tag/2.0.35)

I am still seeing this behaviour in Formie 2.0.44.1 and Craft 4.5.12...

<img width="798" alt="Screenshot 2023-12-15 at 10 55 15" src="https://github.com/verbb/formie/assets/18699249/2fd08075-3464-4121-b068-5865dd0bfef9">

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.44.1"`.

**Comment by engram-design** [comment]
Fixed in [2.0.45](https://github.com/verbb/formie/releases/tag/2.0.45)
