### ISSUE TITLE
Export form submissions does not export form data

### ISSUE THREAD

**Issue by FrancisMawn** [verbb/formie#158]
**Description**
When exporting the form submissions, the actual form data is not exported. This is true for any format (csv, json, xml). 
Only these values get exported:
id, formId, isIncomplete, isSpam, title, dateCreated, dateUpdated, status

![image](https://user-images.githubusercontent.com/45174482/95102758-c6680680-0701-11eb-9424-229b40329909.png)

**Steps to reproduce**
1. Go to /admin/formie/submissions
2. Choose one or more submissions
3. Click on the export button
4. Choose whatever format to export to
5. Export file does not contain form data

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.2.19
- Craft version:   3.5.11.1
- Multi-site: Yes

**Additional context**

**Comment by PatrickMessierGoC** [comment]
Any update on this?

**Comment by engram-design** [comment]
This _was_ working, so seems odd this behaviour has reverted. But I can confirm it doesn't seem to be working now

**Comment by engram-design** [comment]
Looks like this was when exporting when "All Forms" was selected in the sidebar. If you selected the form first, then filtered, this should've worked.

Fixed in [1.2.20](https://github.com/verbb/formie/releases/tag/1.2.20)

**Comment by giorgiopogliani** [comment]
I am testing the export with the new multi site submissions and I am still getting this problem. If I select "All Forms" or if I don't. Maybe the new filter by site is messing up with the exports?

Edit: Actually, this happens only if I don't select any submissions with the checkboxes. I guess if none are selected it should do an export all, which it does, but the form fields are missing.

**Comment by engram-design** [comment]
I tested both selecting some and selecting none, and both seem to work on my end. I've tried:
- "All Forms" with none selected
- "All Forms" with some selected
- "Contact Form" with none selected
- "Contact Form" with some selected
- All of the above from Site 1
- All of the above from Site 2

I _think_ this should be fixed in [1.2.21](https://github.com/verbb/formie/releases/tag/1.2.21).
