### ISSUE TITLE
Bug: Duplicate Files Saved in Form Submission's Multiple File Fields via GraphQL Mutation

### ISSUE THREAD

**Issue by denisyilmaz** [verbb/formie#1611]
### Describe the bug

Problem:
When submitting a form with multiple file fields via GraphQL mutation, the backend is saving duplicate files in each file field. This behavior results in twice as many files being saved in the submission than expected.

**Expected Behavior:**
The expected behavior is that each file field in the form should only contain the file(s) specified in the GraphQL submission for that field, with no duplicates.

**Actual Behavior:**
Upon checking the submission in the backend, it is observed that instead of having one file in each file field, there are duplicates of the specified files in each file field. For example, if two files are selected (one for each file field), the submission will contain four files (two in each file field).

### Steps to reproduce

1. Create a form with multiple file fields
2. Submit the form via a GraphQL mutation, specifying one file for each file field.
3. Check the submission in the backend.

### Form settings

**Additional Information:**
The duplicate files are stored separately in the relative path of each field's settings, confirming that they are distinct files.
The GraphQL submission sent from the frontend correctly specifies one file per field, and there are no error responses from the server.

<img width="251" alt="image" src="https://github.com/verbb/formie/assets/4189607/c9af4789-9e7b-452f-bea9-a4563333c38e">
<img width="278" alt="image" src="https://github.com/verbb/formie/assets/4189607/a5001d53-aeaf-4258-a398-3608064006f1">

### Craft CMS version

4.5.6.1

### Plugin version

2.0.39

### Multi-site?

NO

### Additional context

**Mutation sent to Craft CMS**
```json
{
    "query": "mutation FormMutation($bewerbungFuer: [Int], $anrede: String, $titel: String, $vorname: String, $nachname: String, $eMail: String, $wieSindSieAufUnsAufmerksamGeworden: String, $filefieldone: [FileUploadInput], $filefieldtwo: [FileUploadInput], $ichErlaubeDieVerwendungMeinerGesamtenB: String, $weitergabeIhrerBewerbung: String, $ichHabeDieDatenschutzerklaerungGelesen: String, $recaptchaCaptcha: FormieCaptchaInput) {\n            save_hrworksBewerbung_Submission(bewerbungFuer: $bewerbungFuer, anrede: $anrede, titel: $titel, vorname: $vorname, nachname: $nachname, eMail: $eMail, wieSindSieAufUnsAufmerksamGeworden: $wieSindSieAufUnsAufmerksamGeworden, filefieldone: $filefieldone, filefieldtwo: $filefieldtwo, ichErlaubeDieVerwendungMeinerGesamtenB: $ichErlaubeDieVerwendungMeinerGesamtenB, weitergabeIhrerBewerbung: $weitergabeIhrerBewerbung, ichHabeDieDatenschutzerklaerungGelesen: $ichHabeDieDatenschutzerklaerungGelesen, recaptchaCaptcha: $recaptchaCaptcha) {\n              statusId\n              status\n              isIncomplete\n              title\n              isSpam\n              spamClass\n              spamReason\n            }\n        }",
    "variables": {
        "bewerbungFuer": 102962,
        "anrede": "",
        "titel": "Test",
        "vorname": "Test",
        "nachname": "Test",
        "eMail": "mail@example.com",
        "wieSindSieAufUnsAufmerksamGeworden": "",
        "filefieldone": [
            {
                "filename": "formie-test-1.pdf",
                "fileData": "data:application/pdf;base64,…="
            }
        ],
        "filefieldtwo": [
            {
                "filename": "formie-test-2.pdf",
                "fileData": "data:application/pdf;base64,…="
            }
        ],
        "ichErlaubeDieVerwendungMeinerGesamtenB": "",
        "weitergabeIhrerBewerbung": "",
        "ichHabeDieDatenschutzerklaerungGelesen": "true",
        "recaptchaCaptcha": {
            "name": "g-recaptcha-response",
            "value": "03AFcWeA4z5srx…"
        }
    }
}
```

**Screenshots**
1. File-Field in the form
<img width="380" alt="image" src="https://github.com/verbb/formie/assets/4189607/f06da23b-0054-4840-8b8f-ce9d90ec27a6">
2. Selected files in the frontend
<img width="498" alt="image" src="https://github.com/verbb/formie/assets/4189607/8800cdce-f6f2-48ff-8553-dd3e02b371ab">
3. Mutation in the console
<img width="363" alt="image" src="https://github.com/verbb/formie/assets/4189607/0c1ef029-faee-4a33-8272-5c0470ec5d0a">

**Comment by denisyilmaz** [comment]
Additional Info: we have a "placeholder" asset field on our files. When Formie creates the uploaded assets it somehow also sets this subfield with the duplicate files.

Could this be related to the fix introduces in 2.0.37?
- https://github.com/verbb/formie/commit/430309b0e708d63f875cb037af06de33270044c5 
- https://github.com/verbb/formie/blob/430309b0e708d63f875cb037af06de33270044c5/src/gql/types/input/FileUploadInputType.php#L101

<img width="882" alt="image" src="https://github.com/verbb/formie/assets/4189607/91ed4eb5-d8ce-4c68-85bc-31e1b005ae10">

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by denisyilmaz** [comment]
Hi @engram-design thanks for the quick response. i tested it locally and can still see one issue:
the first field in the submission has all the files in it while the second field only contains the one selected.
<img width="367" alt="image" src="https://github.com/verbb/formie/assets/4189607/d4ce2713-bda4-442c-8911-0f0d84a72706">
<img width="255" alt="image" src="https://github.com/verbb/formie/assets/4189607/2a4e46f1-8be1-4b01-be50-52f3d023acfc">

**Comment by engram-design** [comment]
Ah, missed that. Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.39"`.

**Comment by engram-design** [comment]
Fixed in [2.0.40](https://github.com/verbb/formie/releases/tag/2.0.40)
