### ISSUE TITLE
`ModifyEmailFieldUniqueQueryEvent` deprecation warning

### ISSUE THREAD

**Issue by chrismlusk** [verbb/formie#1669]
### Describe the bug

After updating to 2.1.1, I'm seeing the following deprecation warning:

> The `ModifyEmailFieldUniqueQueryEvent` event has been deprecated. Use the `ModifyFieldUniqueQueryEvent` event instead.

Commit 5b1adddfdf553783904b30406cd3d847d4c239fd may take care of this, but filing it here just in case!

### Craft CMS version

4.5.13

### Plugin version

2.1.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.1"`.

**Comment by chrismlusk** [comment]
@engram-design FWIW, I updated to "dev-craft-4 as 2.1.1" locally, and I see this warning after running `composer install`:

```
Class verbb\formie\events\ModifyFieldUniqueQueryEvent located in ./vendor/verbb/formie/src/base/ModifyFieldUniqueQueryEvent.php does not comply with psr-4 autoloading standard. Skipping.
```

It looks like the `ModifyFieldUniqueQueryEvent.php` file was added to both the `base` and `events` directories in commit 45f4132e194d70511bd81a28ff06b6a1c35b7738, but the namespace for each is `verbb\formie\events`. So I think that's the problem.

However, this brings me to another issue with deprecation warnings.

When I attempt to submit a form that has an Email field with the unique value setting enabled, I get a 500 error. When I check the Network tab in dev tools, the response is the deprecation error that is logged on line 446 in [`FormFieldTrait.php`](https://github.com/verbb/formie/blob/craft-4/src/base/FormFieldTrait.php#L446):

```
'The `ModifyEmailFieldUniqueQueryEvent` event has been deprecated. Use the `ModifyFieldUniqueQueryEvent` event instead.'
```

That's because I have my `config/app.php` file configured to throw exceptions on deprecation warnings in local dev, e.g.:

```php
return [
  'components' => [
    'deprecator' => [
      // Throw exceptions on deprecation warnings
      'throwExceptions' => App::parseBooleanEnv('$HARD_MODE'),
    ],
  ],
];
```

And given that this was code [recommended by Craft](https://craftcms.com/knowledge-base/preparing-for-craft-4#fix-deprecation-warnings) when preparing for Craft 4, I'd bet this isn't an uncommon setting.

I see your note about removing that `if` block at the next breakpoint, and while I can set that my `HARD_MODE` env var to `false` and carry on, I figured I'd document this here since it took a bit of digging on my part to figure out what was going on. Thanks!

**Comment by engram-design** [comment]
Ah, not sure how that slipped in there, but updated in the `craft-4` branch.

And while that `throwExceptions` config is indeed recommended for large upgrades, I wouldn't have thought that it should be enabled all the time? Warnings shouldn't probably be listed as exceptions _all_ the time. But yeah, a bit tricky to handle that otherwise to give people a warning about a breaking issue before Formie 3 without a deprecation notice.

**Comment by chrismlusk** [comment]
Oh for sure. I added that to my config during the upgrade and definitely forgot about it. That's what I meant when saying it might not be totally uncommon. Although on further thought, I personally like getting exceptions locally since they force me to fix deprecations that I introduce in my code. But I see what you mean about plugins needing to warn people in advanced of breaking changes. It is what it is.

**Comment by engram-design** [comment]
For sure, appreciate the note here regardless, and hope it’ll help others if they stumble across this!

**Comment by engram-design** [comment]
Fixed in [2.1.2](https://github.com/verbb/formie/releases/tag/2.1.2)

**Comment by dietervyncke** [comment]
> Ah, not sure how that slipped in there, but updated in the `craft-4` branch.
> 
> And while that `throwExceptions` config is indeed recommended for large upgrades, I wouldn't have thought that it should be enabled all the time? Warnings shouldn't probably be listed as exceptions _all_ the time. But yeah, a bit tricky to handle that otherwise to give people a warning about a breaking issue before Formie 3 without a deprecation notice.

The deprecation warning 'The `ModifyEmailFieldUniqueQueryEvent` event has been deprecated. Use the `ModifyFieldUniqueQueryEvent` event instead' is still present, even on branch 'craft-4'. 

Not sure what the '[ // TODO: to remove at the next breakpoint](https://github.com/verbb/formie/blob/craft-4/src/base/FormFieldTrait.php#L457)' comment is referring to.

### Craft CMS version
4.12.3

### Plugin version
2.1.30

**Comment by engram-design** [comment]
This fix mentioned was an incorrect import https://github.com/verbb/formie/commit/5b1adddfdf553783904b30406cd3d847d4c239fd but that event should still be there, and the deprecation warning, as it's removed in Formie 3.
