### ISSUE TITLE
Error in uninstall migration – Table formie_stencils doesn't exist

### ISSUE THREAD

**Issue by MoritzLost** [verbb/formie#1710]
### Describe the bug

When uninstalling the plugin, I get an error in the console, probably from the uninstall migration. In this case, the plugin is uninstalled by switching to a version of the project config that doesn't include it and running `project-config/apply`.

```
❯ php craft project-config/apply
Uninstalling plugin "formie" ... done
Applying changes from your project config files ...
- removing formie.stencils.a3245ed5-47a0-4295-ac0c-c74cdb459282.data.pages.0.rows.0.fields.0.settings ... 
  - removing meta.__names__.a3245ed5-47a0-4295-ac0c-c74cdb459282 ... done
  - removing formie.stencils.a3245ed5-47a0-4295-ac0c-c74cdb459282 ... 
error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'website.cb_formie_stencils' doesn't exist
The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`
FROM `cb_formie_stencils`
WHERE `dateDeleted` IS NULL
ORDER BY `name`
```

The table prefix in this installation is `cb_`.

Running `project-config/apply` a second time finishes successfully.

I've also noticed that two of formies database tables remain after uninstallation. Not sure if this is intentional or a side-effect of that bug:

- `cb_formie_newlayout`
- `cb_formie_newnestedlayout`

### Steps to reproduce

1. Install the plugin.
2. Run `git stash --include-untracked` to reset the project config to the previous state.
3. Run `php craft project-config/apply`.

### Form settings

N/A

### Craft CMS version

4.7.1

### Plugin version

2.1.3

**Comment by engram-design** [comment]
Those two database tables are new and just for the migration to Formie 3, but they should be included.

Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.3"`.

**Comment by MoritzLost** [comment]
@engram-design Thanks! Does this also fix the error I got when uninstalling the plugin regarding the `formie_stencils` table not existing?

**Comment by engram-design** [comment]
Sorry, I should have mentioned that also - we've changed the [order of operations](https://github.com/verbb/formie/commit/3064623d85ef2eb77f8acc99976619751f4ff8da) where the project config is removed first, then the database tables to get around this issue.

**Comment by MoritzLost** [comment]
@engram-design Great, thanks!

**Comment by engram-design** [comment]
Fixed in [2.1.4](https://github.com/verbb/formie/releases/tag/2.1.4)

**Comment by MangoMarcus** [comment]
I'm still getting this error in 2.1.41

**Comment by engram-design** [comment]
The exact same error as the original issue, or the `formie_stencils` table not existing? Both issues aren't being raised on my end, I'm afraid.

**Comment by MangoMarcus** [comment]
Sorry @engram-design I'm referring to `formie_stencils` not existing. Is the other issue you're referring to the leftover tables? I don't have that, no.

I'm running Formie 2.1.41 and Craft 4.14.4 with ddev

- Run `ddev craft plugin/uninstall formie`
- Re-import DB from before it was uninstalled
- Run `ddev craft up`
- Get error:
    ```
    Checking for pending Craft and plugin migrations ...
    No new migrations found. Your system is up to date.

    Uninstalling plugin "formie" ... done
    Applying changes from your project config files ...
    - removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332.data.pages.0.rows.8.fields.0.settings.description.0.content.0 ...
      - removing meta.__names__.78f9374c-4fc2-42df-8390-cbb1abd82332 ... done
      - removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332 ...
    error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist
    The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`
    FROM `formie_stencils`
    WHERE `dateDeleted` IS NULL
    ORDER BY `name`a
    [2025-02-06T18:38:28.834681+00:00] app.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll() #4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all() #5 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all() #6 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(124): verbb\formie\services\Stencils->getAllStencils() #7 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(333): verbb\formie\services\Stencils->getStencilByUid() #8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Stencils->handleDeletedStencil() #9 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #10 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #11 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #12 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #13 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #14 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #15 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #18 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #19 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #20 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #23 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #25 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #26 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #29 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #30 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #31 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #32 [internal function]: craft\console\controllers\UpController->actionIndex() #33 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #34 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #35 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #37 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #38 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #39 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #40 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #41 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #42 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #43 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #44 /var/www/html/craft(13): yii\base\Application->run() #45 {main}  Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid` FROM `formie_stencils` WHERE `dateDeleted` IS NULL ORDER BY `name` in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll() #4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all() #5 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all() #6 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(124): verbb\formie\services\Stencils->getAllStencils() #7 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(333): verbb\formie\services\Stencils->getStencilByUid() #8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Stencils->handleDeletedStencil() #9 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #10 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #11 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #12 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #13 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #14 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #15 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #18 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #19 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #20 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #23 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #25 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #26 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #29 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #30 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #31 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #32 [internal function]: craft\console\controllers\UpController->actionIndex() #33 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #34 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #35 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #37 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #38 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #39 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #40 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #41 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #42 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #43 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #44 /var/www/html/craft(13): yii\base\Application->run() #45 {main} Additional Information: Array (     [0] => 42S02     [1] => 1146     [2] => Table 'db.formie_stencils' doesn't exist )  {"trace":[],"memory":11483464,"category":"yii\\db\\Exception","timestamp":1738867108.791081,"exception":"[object] (yii\\db\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist\nThe SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`\nFROM `formie_stencils`\nWHERE `dateDeleted` IS NULL\nORDER BY `name` at /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist at /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320)"} []
    ```
- Run ddev craft `project-config/apply`
- Finishes successfully

It appears a reference to `formie_stencils` still exists (or is re-added) in the cached project config

**Comment by engram-design** [comment]
Oh right, I see what you're doing! Yes, project config changes are happening before Formie has installed. That's actually interesting that this isn't handled for other plugins like Commerce.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.41"`.

**Comment by MangoMarcus** [comment]
Thanks @engram-design , it's gotten further but still getting a similar issue - this time with the `formie_integrations` table 😁 

Sorry!

```
Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.

Uninstalling plugin "formie" ... done
Applying changes from your project config files ...
- removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332.data.pages.0.rows.8.fields.0.settings.description.0.content.0 ...
  - removing meta.__names__.78f9374c-4fc2-42df-8390-cbb1abd82332 ... done
  - removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332 ... done
  done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.4 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.5 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.6 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.7 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.8 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3.1.__assoc__.10 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.4 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.5 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.6 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3.1.__assoc__.7 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.3.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.3.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.4.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.5.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.6.1.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.0.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.1.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.2.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.3.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.4.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.4.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.4.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.4.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.5.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.5.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.5.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.5.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.6.1.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.6.1.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.6.1.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.6.1.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.0 ... done
- removing plugins.formie.settings.captchas.__assoc__.1 ... done
- removing plugins.formie.settings.captchas.__assoc__.2 ... done
- removing plugins.formie.settings.captchas.__assoc__.3 ... done
- removing plugins.formie.settings.captchas.__assoc__.4 ... done
- removing plugins.formie.settings.captchas.__assoc__.5 ... done
- removing plugins.formie.settings.captchas.__assoc__.6 ... done
- removing formie.integrations.2d109c9c-2397-41d6-a90f-c3bda9a84eae.settings ...
  - removing meta.__names__.2d109c9c-2397-41d6-a90f-c3bda9a84eae ... done
  - removing formie.integrations.2d109c9c-2397-41d6-a90f-c3bda9a84eae ...
error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_integrations' doesn't exist
The SQL being executed was: SELECT *
FROM `formie_integrations`
WHERE (`formie_integrations`.`dateDeleted` IS NULL) AND (`uid`='2d109c9c-2397-41d6-a90f-c3bda9a84eae')
[2025-02-07T23:05:54.965896+00:00] app.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_integrations' doesn't exist in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne() #4 /var/www/html/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one() #5 /var/www/html/vendor/verbb/formie/src/services/Integrations.php(916): yii\db\ActiveQuery->one() #6 /var/www/html/vendor/verbb/formie/src/services/Integrations.php(570): verbb\formie\services\Integrations->_getIntegrationRecord() #7 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Integrations->handleDeletedIntegration() #8 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #10 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #12 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #13 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #14 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #15 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #18 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #19 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #20 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #21 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #22 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #23 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #25 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #26 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #27 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #29 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #30 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #31 [internal function]: craft\console\controllers\UpController->actionIndex() #32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #34 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #35 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #37 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #38 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #39 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #40 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #41 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #42 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #43 /var/www/html/craft(13): yii\base\Application->run() #44 {main}  Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_integrations' doesn't exist The SQL being executed was: SELECT * FROM `formie_integrations` WHERE (`formie_integrations`.`dateDeleted` IS NULL) AND (`uid`='2d109c9c-2397-41d6-a90f-c3bda9a84eae') in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Command->queryOne() #4 /var/www/html/vendor/yiisoft/yii2/db/ActiveQuery.php(304): yii\db\Query->one() #5 /var/www/html/vendor/verbb/formie/src/services/Integrations.php(916): yii\db\ActiveQuery->one() #6 /var/www/html/vendor/verbb/formie/src/services/Integrations.php(570): verbb\formie\services\Integrations->_getIntegrationRecord() #7 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Integrations->handleDeletedIntegration() #8 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #9 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #10 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #11 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #12 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #13 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #14 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #15 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #18 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #19 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #20 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #21 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #22 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #23 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #25 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #26 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #27 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #28 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #29 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #30 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #31 [internal function]: craft\console\controllers\UpController->actionIndex() #32 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #33 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #34 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #35 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #37 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #38 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #39 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #40 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #41 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #42 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #43 /var/www/html/craft(13): yii\base\Application->run() #44 {main} Additional Information: Array (     [0] => 42S02     [1] => 1146     [2] => Table 'db.formie_integrations' doesn't exist )  {"trace":[],"memory":12818280,"category":"yii\\db\\Exception","timestamp":1738969554.864887,"exception":"[object] (yii\\db\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_integrations' doesn't exist\nThe SQL being executed was: SELECT *\nFROM `formie_integrations`\nWHERE (`formie_integrations`.`dateDeleted` IS NULL) AND (`uid`='2d109c9c-2397-41d6-a90f-c3bda9a84eae') at /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_integrations' doesn't exist at /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320)"} []
```

**Comment by engram-design** [comment]
@MangoMarcus Just pushed another fix for that, which should hopefully address it.

To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.41"`.

**Comment by MangoMarcus** [comment]
Sorry @engram-design , back to the formie_stencils error now!

```
Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.

Uninstalling plugin "formie" ... done
Applying changes from your project config files ...
- removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332.data.pages.0.rows.8.fields.0.settings.description.0.content.0 ...
  - removing meta.__names__.78f9374c-4fc2-42df-8390-cbb1abd82332 ... done
  - removing formie.stencils.78f9374c-4fc2-42df-8390-cbb1abd82332 ...
error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist
The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`
FROM `formie_stencils`
WHERE `dateDeleted` IS NULL
ORDER BY `name`
[2025-02-10T23:51:59.226172+00:00] app.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll() #4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all() #5 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all() #6 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(124): verbb\formie\services\Stencils->getAllStencils() #7 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(333): verbb\formie\services\Stencils->getStencilByUid() #8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Stencils->handleDeletedStencil() #9 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #10 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #11 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #12 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #13 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #14 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #15 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #18 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #19 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #20 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #23 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #25 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #26 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #29 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #30 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #31 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #32 [internal function]: craft\console\controllers\UpController->actionIndex() #33 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #34 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #35 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #37 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #38 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #39 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #40 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #41 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #42 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #43 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #44 /var/www/html/craft(13): yii\base\Application->run() #45 {main}  Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid` FROM `formie_stencils` WHERE `dateDeleted` IS NULL ORDER BY `name` in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676 Stack trace: #0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException() #1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute() #2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal() #3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll() #4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(252): yii\db\Query->all() #5 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all() #6 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(124): verbb\formie\services\Stencils->getAllStencils() #7 /var/www/html/vendor/verbb/formie/src/services/Stencils.php(333): verbb\formie\services\Stencils->getStencilByUid() #8 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1160): verbb\formie\services\Stencils->handleDeletedStencil() #9 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #10 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #11 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #12 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1150): craft\models\ProjectConfigData->commitChanges() #13 [internal function]: craft\services\ProjectConfig->handleChangeEvent() #14 /var/www/html/vendor/yiisoft/yii2/base/Component.php(641): call_user_func() #15 /var/www/html/vendor/craftcms/cms/src/models/ProjectConfigData.php(79): yii\base\Component->trigger() #16 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1273): craft\models\ProjectConfigData->commitChanges() #17 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(1279): craft\services\ProjectConfig->craft\services\{closure}() #18 /var/www/html/vendor/craftcms/cms/src/services/ProjectConfig.php(593): craft\services\ProjectConfig->_applyChanges() #19 /var/www/html/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(329): craft\services\ProjectConfig->applyExternalChanges() #20 [internal function]: craft\console\controllers\ProjectConfigController->actionApply() #21 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #22 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #23 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #24 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #25 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #26 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #29 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction() #30 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run() #31 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(76): craft\console\Controller->run() #32 [internal function]: craft\console\controllers\UpController->actionIndex() #33 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #34 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams() #35 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction() #36 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction() #37 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction() #38 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction() #39 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #40 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction() #41 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction() #42 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest() #43 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest() #44 /var/www/html/craft(13): yii\base\Application->run() #45 {main} Additional Information: Array (     [0] => 42S02     [1] => 1146     [2] => Table 'db.formie_stencils' doesn't exist )  {"trace":[],"memory":12459440,"category":"yii\\db\\Exception","timestamp":1739231519.169923,"exception":"[object] (yii\\db\\Exception(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist\nThe SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`\nFROM `formie_stencils`\nWHERE `dateDeleted` IS NULL\nORDER BY `name` at /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.formie_stencils' doesn't exist at /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320)"} []
```

**Comment by engram-design** [comment]
Huh, I couldn't actually replicate that one and [my fix](https://github.com/verbb/formie/blob/789a454f41a57e66e54447323391263e01772a9e/src/Formie.php#L487-L490) should've taken care of that, I would think. I'll keep looking into it.

**Comment by engram-design** [comment]
Updated in [4.0.0-beta.10](https://github.com/verbb/formie/releases/tag/4.0.0-beta.10).
