### ISSUE TITLE
Setting checkbox field to 'required' needs all values checked

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#194]
**Description**
I don't think this is me, but I have two checkbox fields, both of which are marked as 'required'. But the form refuses to submit unless all values in those fields are checked. 

**Steps to reproduce**
1. Set up a checkbox field as a 'required field'
2. Try to submit the form on the front end
3. Unless all values are selected, the form will tell you that "this field is required".

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.24
- Craft version: Craft Pro 3.5.14
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.24",
  "...": "..."
}
```

Then run `composer update`.

**Comment by AndrewMac** [comment]
Thanks so much for that. I checked the dev release, and everything seems to be working fine, both with the 'required' issue and with sending the checkbox data through to Campaign. I'll close this for you now :-)

**Comment by engram-design** [comment]
Fixed in [1.2.25](https://github.com/verbb/formie/releases/tag/1.2.25)

**Comment by Timusan** [comment]
I'm afraid their could be regression on this issue as I see this reoccurring in the latest release. I am again forced to check all checkboxes in a required Checkboxes field. Checking a single option will print a validation error next to the remaining ones and validation only passes when all of them are checked.

This is happening on Formie release: 1.3.2.

**Comment by Timusan** [comment]
Aha, nested fields strike again ... this only happens when the Checkbox field is wrapped in a Group (in my case). When I recreate the field outside of the Group it validates as expected.

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)

**Comment by fredrik-sogaard** [comment]
I'm running version 1.3.3 and experience this issue still. See this: https://cln.sh/p2qZim Any way of working around this?

**Comment by engram-design** [comment]
@fredrik-sogaard There's been a bunch of changes since 1.3.3, particularly [1.4.15](https://github.com/verbb/formie/blob/craft-3/CHANGELOG.md#1415---2021-09-04) which fixes a few of these issues with checkboxes.

**Comment by fredrik-sogaard** [comment]
I meant to say I’m running the latest version of Formie. Sorry for being unclear. This happens on the latest version for me.
________________________________
Fra: Josh Crawford ***@***.***>
Sendt: Saturday, September 18, 2021 12:15:31 AM
Til: verbb/formie ***@***.***>
Kopi: Fredrik Søgaard ***@***.***>; Mention ***@***.***>
Emne: Re: [verbb/formie] Setting checkbox field to 'required' needs all values checked (#194)


@fredrik-sogaard<https://github.com/fredrik-sogaard> There's been a bunch of changed since 1.3.3, particularly 1.4.15<https://github.com/verbb/formie/blob/craft-3/CHANGELOG.md#1415---2021-09-04> which fixes a few of these issues with checkboxes.

**Comment by engram-design** [comment]
@fredrik-sogaard are you using custom templates? Are you using the default JS in Formie?

do you have client side validation enabled? Either as you type on on submit.

I can’t relocate this behavior though on 1.4.17

**Comment by fredrik-sogaard** [comment]
I found the issue and it's on our side: We're still on Craft 3.5 on this project and that's why we didn't see any Formie update messages from Craf. I thought we were on the latest Formie version because of this, but hadn't looked close enough. Sorry!
