### ISSUE TITLE
Assign to user group not working on user registration form

### ISSUE THREAD

**Issue by bfjare** [verbb/formie#1969]
### Describe the bug

When submitting a user registration form it successfully creates a user but doent not assign them to the correct user group.

![Screenshot 2024-07-05 at 3 33 59 PM](https://github.com/verbb/formie/assets/11744681/5d4d8288-eb1c-4ee9-8ef7-9adc2a903ded)
![Screenshot 2024-07-05 at 3 34 15 PM](https://github.com/verbb/formie/assets/11744681/33249a77-af24-4c25-b359-e3b8db40fb5c)

### Steps to reproduce

1.  Create registration form and select a user group with a user element applied to the form.
2. Submit form 

### Form settings

- Multi-page form:  No
- Submission Method:  Page Reload
- Client-side Validation:  Yes
- Custom Form Templates: No

### Craft CMS version

 5.2.5

### Plugin version

3.0.0-beta.16

### Multi-site?

No

**Comment by engram-design** [comment]
Hmm, that does seem to be working for me. Can you let me know the rest of the settings for the integration (under Form > Integrations), just in case that's a factor?

**Comment by bfjare** [comment]
![Screenshot 2024-07-06 at 11 14 37 AM](https://github.com/verbb/formie/assets/11744681/02ddf525-0d1e-4761-b1b7-255c53e70aab)
![Screenshot 2024-07-06 at 11 14 59 AM](https://github.com/verbb/formie/assets/11744681/a5f3f046-dd81-4b9a-8397-638f8369acd0)
![Screenshot 2024-07-06 at 11 15 12 AM](https://github.com/verbb/formie/assets/11744681/b7f1a047-8f9e-40fe-8f56-b0654e5a9598)

**Comment by engram-design** [comment]
Thanks for confirming, and just tested with that replicated setup. Strangely, it still is working for me. Anything else plugin-wise on your end that might be interfering?

**Comment by richardwiggins** [comment]
I'm just trialling Formie for the first time and having the exact same issue. @bfjare Did you find the issue?

Using Craft 4.13.2

**Comment by engram-design** [comment]
Nothing in your /storage/logs/formie.log files about any potentially issues?

If you have a look at the source for the User checkbox fields, and the User Group fields, do the values match between them?

**Comment by richardwiggins** [comment]
Nothing in the logs really:
`2024-11-26 14:43:58 [ERROR] Notification email error. No recipient email address found.
2024-11-26 14:43:58 [INFO] Request context:
$_GET = [
    'p' => 'admin/actions/formie/email/preview'
    'site' => 'default'
    'v' => '1732632238537'
]`

> User checkbox fields

?

**Comment by richardwiggins** [comment]
<img width="1104" alt="Screenshot 2024-11-27 at 11 06 14" src="https://github.com/user-attachments/assets/f55c3dab-6dd5-4720-af2f-65576186af17">

It's also set to Activate User, which isn't happening either.

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.33"`. Do note that you may need to update your User Group values, as these have been swapped to UIDs rather than IDs to identify things.

**Comment by richardwiggins** [comment]
Hhhmm, just did an update and it's still not assigning to any groups. It's also still not activating the user, which is set.

**Comment by richardwiggins** [comment]
Hi again, sorry to hassle but was wondering if you had any further ideas. Just tested again and it's still not assigning to groups or activating the user, even though that option is on in the _Integration_.

**Comment by engram-design** [comment]
I've just added a few more areas for logging for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.33"`. If you're able to run that, hopefully we should see any issues in `/storage/logs/formie.log`

**Comment by richardwiggins** [comment]
Nothing is being logged when registering users still unfortunately. Just tried this update. Worth be upgrading to Craft 5 maybe? It's something I need to do with this site at some point anyway.

**Comment by engram-design** [comment]
Strange that nothing is getting logged. No need to upgrade to Craft 5 at this stage.

Failing all that, we can start manually debugging the integration if that's something you're up for? We'd just be adding debug statements to the integration code to step through how things are progressing.

To do this, first head to Formie > Settings > Submissions and turn off the **Use Queue for Integrations** setting. This will make debugging easier in "real time" rather than use the queue, which is tricky to see output for.

Next, head to your `/vendor/verbb/formie/src/integrations/elements/User.php` file. On [this line](https://github.com/verbb/formie/blob/40e6437f1517e665634868b80f6b159cb7bc8d8c/src/integrations/elements/User.php#L183) let's start adding a simple debug statement of `Craft::dd('user integration');`.

Go to the front-end of your form, hit submit and you should see this debug statement. If you have an Ajax-enabled form you'll need to inspect the network request in your web developer tools, or switch to Page Reload for easier debugging.

If that's all gone well, we can start stepping through each action about user groups and user activation.

The next would be to check for `Craft::dd($userGroups);` [here](https://github.com/verbb/formie/blob/40e6437f1517e665634868b80f6b159cb7bc8d8c/src/integrations/elements/User.php#L210). Then `Craft::dd($user->getStatus());` [here](https://github.com/verbb/formie/blob/40e6437f1517e665634868b80f6b159cb7bc8d8c/src/integrations/elements/User.php#L282)

Let me know if you're able to make those changes locally to test.

**Comment by richardwiggins** [comment]
I've done those steps, though not added user groups etc yet.

Weirdly I'm still getting nothing in the Formie logs after submitting the form, though it has registered a user, without assigning to a group.

For ref, my form embed code is below and I'm currently just using all default templates for now with no changes:
```
{% set form = craft.formie.forms.handle('register').one() %}
{% do craft.formie.registerAssets(form) %}
<form method="post" accept-charset="UTF-8" data-fui-form="{{ form.configJson }}">
	{{ actionInput('users/save-user') }}
	{{ csrfInput() }}

	{{ craft.formie.renderPage(form, null, {
		fieldNamespace: '',
	}) }}
</form>
```

**Comment by engram-design** [comment]
Aha, that would be what's going on. You're changing the action to go to `users/save-user` and not `formie/submissions/submit`. As such, it's not even hitting Formie to make a submission or fire integrations.

You'll need to be **either** the [Craft-based form](https://verbb.io/craft-plugins/formie/docs/template-guides/craft-forms#user-registration) scenario, where you get the benefits of a content managed form, but you don't get any submissions, email notifications or integrations.

If you route it through Formie like a regular form, you can still register users, using the User Element integration. You've also got a lot more options doing that. The potential downside to this approach is that you may not want a Submission created for each registration, but that may also be beneficial.

**Comment by richardwiggins** [comment]
Aaahhhh 🤦 

Cool, updated and Formie log is being updated, but I got an error back:

`verbb\formie\controllers\SubmissionsController::_getForm(): Argument #1 ($handle) must be of type string, null given, called in /Users/richardwiggins/Dropbox/Sites/protospace-main.local/craft/vendor/verbb/formie/src/controllers/SubmissionsController.php on line 460`

**Comment by engram-design** [comment]
Can you share your updated code? You'll also want to remove `fieldNamespace: '',` as that'll disrupt Formie.

If you're not already, I'd suggest swapping back to `{{ craft.formie.renderForm(form) }}`

**Comment by richardwiggins** [comment]
I've reverted to `{{ craft.formie.renderForm(form) }}` and pleased to see it's working much better 🙌 

Still not registering the user but getting somewhere. Here's the logs:

```
2024-12-13 11:56:55 [INFO] Submission triggered for .
2024-12-13 11:56:55 [INFO] Request context:
$_GET = [
    'p' => 'register'
]

$_POST = [
    'action' => 'formie/submissions/submit'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'firstName' => 'Richard'
    'lastName' => 'Wiggins'
    'email' => 'richardpixel@gmail.com'
    'password' => '•••••••'
    'submitAction' => 'submit'
]
2024-12-13 12:08:56 [INFO] Submission triggered for register.
2024-12-13 12:08:56 [INFO] Request context:
$_GET = [
    'p' => 'register'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'formie/submissions/submit'
    'submitAction' => 'submit'
    'handle' => 'register'
    'siteId' => '1'
    'fields' => [
        'firstName' => 'Richard'
        'lastName' => 'Wiggins'
        'email' => 'richardpixel@gmail.com'
        'password' => '••••'
        'instagram' => ''
        'linkedin' => ''
        'x' => ''
        'youtube' => ''
    ]
]
2024-12-13 12:12:32 [INFO] Submission triggered for register.
2024-12-13 12:12:32 [INFO] Request context:
$_GET = [
    'p' => 'register'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'formie/submissions/submit'
    'submitAction' => 'submit'
    'handle' => 'register'
    'siteId' => '1'
    'submissionId' => '13422'
    'fields' => [
        'firstName' => 'Richard'
        'lastName' => 'Wiggins'
        'email' => 'richardpixel@gmail.com'
        'password' => '••••'
        'instagram' => 'https://www.instagram.com/richardwiggins/'
        'linkedin' => 'https://www.linkedin.com/in/richardpixel/'
        'x' => ''
        'youtube' => ''
    ]
]
2024-12-13 12:15:39 [INFO] Submission triggered for register.
2024-12-13 12:15:39 [INFO] Request context:
$_GET = [
    'p' => 'register'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'formie/submissions/submit'
    'submitAction' => 'submit'
    'handle' => 'register'
    'siteId' => '1'
    'fields' => [
        'firstName' => 'Richard'
        'lastName' => 'Wiggins'
        'email' => 'richardpixel@gmail.com'
        'password' => '•••••••'
        'instagram' => ''
        'linkedin' => ''
        'x' => ''
        'youtube' => ''
    ]
]
2024-12-13 12:16:07 [INFO] Submission triggered for register.
2024-12-13 12:16:07 [ERROR] Protospace User: Unable to validate “protospaceUser” element integration. Error: {"email":["Email cannot be blank."]}.
2024-12-13 12:16:07 [ERROR] Element integration failed for submission “13424”. Error: Unable to validate “protospaceUser” element integration. Error: {"email":["Email cannot be blank."]}. /Users/richardwiggins/Dropbox/Sites/protospace-main.local/craft/vendor/verbb/formie/src/base/Integration.php:119
2024-12-13 12:16:07 [INFO] Request context:
$_GET = [
    'p' => 'register'
]

$_POST = [
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'formie/submissions/submit'
    'submitAction' => 'submit'
    'handle' => 'register'
    'siteId' => '1'
    'submissionId' => '13424'
    'fields' => [
        'firstName' => 'Richard'
        'lastName' => 'Wiggins'
        'email' => 'richardpixel@gmail.com'
        'password' => '•••••••'
        'instagram' => 'https://www.instagram.com/richardwiggins/'
        'linkedin' => 'https://www.linkedin.com/in/richardpixel/'
        'x' => ''
        'youtube' => ''
    ]
]
```

**Comment by richardwiggins** [comment]
Ignore that, I needed to re-map the user attribute fields.

As I have `'useEmailAsUsername' => true,` set in config, do the User Fields 'username' and 'email' both need to be mapped to the 'email' Form Field?

And thanks for your help, sorry for being a muppet!

**Comment by engram-design** [comment]
At the moment, both username and email are required, but if you have `useEmailAsUsername` they can both just be the email field in your form.

Glad we got to the bottom of it all!

**Comment by richardwiggins** [comment]
Great, thanks!
