### ISSUE TITLE
Unable to add fields to form [PostgreSQL]

### ISSUE THREAD

**Issue by umkasanki** [verbb/formie#202]
**Description**
When I try add fields to form on the server with PostgreSQL., I get the error:

```{"error":"SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"new8829-1165\"\nThe SQL being executed was: SELECT EXISTS(SELECT *\nFROM \"fields\"\nWHERE (\"fields\".\"handle\"='newField') AND (\"fields\".\"context\" IS NULL) AND (NOT (\"fields\".\"id\"='new8829-1165')))"}```

![изображение](https://user-images.githubusercontent.com/496132/97863665-653f4d00-1d18-11eb-93ec-bf4dae0a4ab0.png)

(On local machine with Mysql it works good)

**Steps to reproduce**
1. Add new form
2. Try to add fields to the form

### Form settings
Empty form with defaut settings

- Multi-page form: Yes 
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.2.25
- Craft version: 3.5.14
- Multi-site: Yes

**Additional context**
PostgreSQL

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.25",
  "...": "..."
}
```

Then run `composer update`.

**Comment by umkasanki** [comment]
Awesome!
Thanks Josh.

**Comment by umkasanki** [comment]
I tried to update plugin.
Error on save form with new field still happens
`{"error":"SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"fmc_newform\" does not exist\nThe SQL being executed was: ALTER TABLE \"fmc_newform\" ADD \"field_newField\" varchar(255)"}`

Also I can't remove forms.
Server response:
`{"error":"SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"fmc_newform\" does not exist\nThe SQL being executed was: ALTER TABLE \"fmc_newform\" RENAME TO \"fmcd_newform_1\""}`

Could you check it?

**Comment by engram-design** [comment]
Hmmm, does creating a new form change anything? I did create a new form to test without issue. It looks like the `fmc_newform` content table didn't get created?

**Comment by umkasanki** [comment]
Forms list
![изображение](https://user-images.githubusercontent.com/496132/98217108-103f4900-1f5b-11eb-9781-d94582ab390b.png)
very strange...

**Comment by engram-design** [comment]
Alrighty, so after adding and deleting a few forms, looks like I can reproduce your error. Might have something to do with how we soft-delete forms.

**Comment by umkasanki** [comment]
Thanks so much for fast reply.

p.s. I really look forward to a prompt solution to this problem. I was very inspired by your plugin and advised colleagues and the client to use it instead of FF in the future. It will be very inconvenient if I miss the deadline in the first project with Formie ...

**Comment by engram-design** [comment]
I've just pushed a fix for this. I believe it was due to a deleted form and trying to create a new form with that same name. The foreign keys weren't correctly renamed like the table was. MySQL seems to be okay with this, but Postgres not so much. In any case, it was technically wrong.

You might need to run Craft's garbage collection - `./craft gc` after updating to clear out old content tables. I would also try re-saving the form as-is, then try adding a field. New forms shouldn't have any issues.

Let me know how you go?

**Comment by umkasanki** [comment]
Unfortunately, I don't have SSH access to run the `./craft gc`
and the old forms are not deleted yet.
But new forms and fields are added fine, that's great.
Thanks

**Comment by engram-design** [comment]
Sure thing, I'd just made sure to manually remove any `fmcd_*` database tables if this problem crops up again.

**Comment by umkasanki** [comment]
ok. I'll keep that in mind.

**Comment by engram-design** [comment]
Should be fixed in [1.2.26](https://github.com/verbb/formie/releases/tag/1.2.26).
