### ISSUE TITLE
HubSpot integration with multiple files not submitting correctly

### ISSUE THREAD

**Issue by wirebone** [verbb/formie#2628]
### Describe the bug

I have a form with a file upload field that can take multiple files that needs to integrate into HubSpot.

If a single file is sent then it work fine. If multiple files are sent then it works but HubSpot sees it as one file and fails to load it. See images below to see the different between a HubSpot form submission and a Formie form submission. Clicking the Formie link inside HubSpot just breaks and says: _"There was a problem loading the submission."_ as it tries to load both images at once. Trying to access each file directly by editing the link also doesn't work. This is what the link it looks like: e.g. https://app.hubspot.com/submissions/xxxxxxxx/form/xxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxx/submissions/test-image.png,%20xxxxxxx-xxxxxx-test.png

Formie submission with HubSpot:
<img width="347" height="72" alt="Image" src="https://github.com/user-attachments/assets/a0e93ccf-1c6b-4235-a338-ba26720f303f" />

Hubspot form submission:
<img width="347" height="61" alt="Image" src="https://github.com/user-attachments/assets/3f9c62e7-b130-4e8d-8cb4-d877d1cc7bdc" />

### Steps to reproduce

1. create an form with a file upload field that can take multiple files
2. integrate with a hubspot field that can also take multiple files
3. submit form to hubspot
4. open the submission and try and open the attachment(s)

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes 
- Custom Form Templates: No

### Craft CMS version

5.8.19

### Plugin version

3.1.5

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.5"`.

**Comment by wirebone** [comment]
Thanks for this. It now separates the files in HubSpot however the files still don't work and throw the same error.

I found that if my file system is set to a private location without a Public URL inside the '/storage' folder then it just throws an error when trying to open it image within HubSpot. Looking at the console errors, it says it's a 404.

If I set the file location to a folder with a Public URL then it does submit it up to HubSpot and you can download it but it keeps setting the extension to '.unknown'. This is the case for .jpg, .png and .pdf files. If you download the file and change the extension back to the original then it seems fine.

**Comment by wirebone** [comment]
As a side note, this seems to have been happening before this latest fix as well.

**Comment by engram-design** [comment]
So that’ll be correct, you need to use a public filesystem for this to work, as we don’t upload the file to HubSpot, merely just referencing it via a link.

I don’t _think_ the HubSpot Forms API allows for us to upload the raw files to HubSpot, but I’d need to check.

As for the missing extension, that seems odd! I’ve been testing on my end just with plain PNG and JPG files and they are solving correctly for me.

**Comment by wirebone** [comment]
Thanks Josh.

I will do some more testing that's not behind an restricted area. It would be good if we could upload the images as we weren't planning on storing them on the server.

**Comment by wirebone** [comment]
Hi Josh,

I have tested with single and multiple files while also being accessible via a public URL with no authentication in front of it but still the file extensions are set as .unknown. Any ideas on what it could be?

**Comment by wirebone** [comment]
@engram-design The issue with the file extension set to .unknown was a result of have `revAssetUrls(true)`. This results in file URLs like `image.jpg?v=545656765` with versions at the end of the filenames and so HubSpot doesn't know what it is.

Is it possible to slice any version control off the end of the filenames when uploading to HubSpot?

**Comment by engram-design** [comment]
Thanks for investigating that further, how interesting! I suppose that’s down to how HubSpot handles that, but yeah I think that’s something we can just manually handle stripping off that data.

**Comment by engram-design** [comment]
Pushed that fix for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.1.5"`.

**Comment by wirebone** [comment]
@engram-design That works perfectly.

You are amazing. Thanks so much for all your help and quick fixes. There is a reason why we have Formie and other Verbb plugins on all our sites.
