### ISSUE TITLE
Recipient email not found when using dynamic value for email

### ISSUE THREAD

**Issue by stevefloat** [verbb/formie#280]
When setting up a new form, or even when looking at your 'stencil' form "Contact form", notification emails don't send when the recipient field contains a dynamic value. When hard-coding a recipient email address the notification **does** send.

**Steps to reproduce**
1. Set up a new notification and assign a dynamic recipient email - see screenshot:
<img width="921" alt="recipient" src="https://user-images.githubusercontent.com/52162823/103899435-4e3d2280-50ee-11eb-83ba-d171bc6fdb53.png">

2. Submit the form - no notification sent and error log (storage/logs/formie.log) reports as follows:
$_POST = []
2021-01-04 16:59:04 [-][1][-][error][formie] Notification email error. No recipient email address found.
2021-01-04 16:59:04 [-][1][-][info][formie] Fail alert not configured to send.
2021-01-04 16:59:03 [-][1][-][info][application] $_GET = []

3. Or preview in UI, which shows same error - see screenshot:
<img width="923" alt="preview" src="https://user-images.githubusercontent.com/52162823/103899586-83e20b80-50ee-11eb-921d-9a661bcec7c4.png">

**Additional info**
- Plugin version: (trial) 1.3.7
- Craft version: (Pro) 3.5.13.2
- Multi-site: No

**Additional context**
We are using the trial version of the plugin. I have tried this in both local environment and on a public staging server. Same result in both instances.

Please let me know if you need any other info. Thanks in advance for any help!

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.7",
  "...": "..."
}
```

Then run `composer update`. You may also need to remove the variable tag for the field and add it again - this includes for the default Stencil. We've recently re-worked how the content for these variables are parsed/stored.

Just let me know if there's still an issue in the meantime.

**Comment by stevefloat** [comment]
Great - thanks Josh. Will check it out.

What's your timeframe on this next release?

**Comment by engram-design** [comment]
Probably 1-2 days at the moment!

**Comment by engram-design** [comment]
Fixed in [1.3.8](https://github.com/verbb/formie/releases/tag/1.3.8).

**Comment by stevefloat** [comment]
Thanks Josh - this has fixed the specific issue I mentioned about recipient email.

However I can see that another, related issue, is still present.

When you add a dynamic variable into the message field, like so:

<img width="935" alt="notification" src="https://user-images.githubusercontent.com/52162823/104165630-8c3d8d80-53f1-11eb-9776-cfcb7d8af220.png">

The message in the received email is blank. This is confirmed in the sent mail screen and notification preview screen:

<img width="933" alt="preview" src="https://user-images.githubusercontent.com/52162823/104165689-a5463e80-53f1-11eb-9fbc-fd51ad9ab9e8.png">

This is the error from the log:
2021-01-11 09:39:09 [-][1][-][error][formie] Failed to render dynamic string “<p>Hi {field.yourFullName}</p><p>Thank you for submitting your enquiry.</p><p>We will get back to you shortly</p><p></p>”. Template error: “An exception has been thrown during the rendering of a template ("Array to string conversion") in "__string_template__2a59ba5859f4c360fa6761ecc2065597da280d4be0acd93c6f637498e03a2638" at line 1.” /Applications/MAMP/htdocs/selby/vendor/twig/twig/src/Template.php:421
2021-01-11 09:39:08 [-][1][-][info][application] $_GET = []

Is this related to the above issue?

Thanks for your help so far.

**Comment by engram-design** [comment]
Should be fixed in [1.3.9](https://github.com/verbb/formie/releases/tag/1.3.9)

**Comment by stevefloat** [comment]
Thanks Josh.

**Comment by giorgiopogliani** [comment]
I am still getting this error on multiple websites, I updated one to the latest version (1.4.16) but it keeps happening. I have no other clue besides the error in the queue: 
```
Failed to send notification email: {"error":"Notification email error. No recipient email address found."}.
```

**Comment by engram-design** [comment]
@giorgiopogliani Are you able to look in the `storage/logs/formie.log` file for any clues?

This error points that the "Recipients" field is empty. Can you provide me the value of that field for your notification? If you're using a variable, it's possible that's evaluating to an empty string.

**Comment by giorgiopogliani** [comment]
Ok, It was unable to write in the cache directory... I don't know how I couldn't see this. 

Anyway, It seems to work now. Thanks!

**Comment by jeffaglenn** [comment]
I'm having kind of the same issue and I feel like I'm just missing something cause from everything I'm reading this shouldn't be an issue. I have my recipients field with multiple emails addresses:

<img width="1092" alt="Screen Shot 2022-01-17 at 1 36 12 PM" src="https://user-images.githubusercontent.com/34280463/149828586-1a6e1bf9-25df-440e-b6aa-0bd55a54f80b.png">

Then I have my Email Notification set up to pull from the field:

<img width="888" alt="Screen Shot 2022-01-17 at 1 39 34 PM" src="https://user-images.githubusercontent.com/34280463/149828751-289183df-f997-4776-8271-2c4b922df7a4.png">

When I submit a test it's pulling the Email Address ID instead of the email address:

<img width="995" alt="Screen Shot 2022-01-17 at 1 41 51 PM" src="https://user-images.githubusercontent.com/34280463/149829029-576970ee-2686-4888-901b-5e334981c007.png">

Am I doing something wrong?
