### ISSUE TITLE
Tag JS and CSS don't load if tags are in a group

### ISSUE THREAD

**Issue by d-karstens** [verbb/formie#345]
**Description**
We've been experiencing an issue with the JS for tags not being available if tag fields are inside a group element, and there are other fields before the tags.

Temporarily fixed this by having a tag outside of the group with a hidden class

**Steps to reproduce**
1. Create a new form with any field first and a tag field second
2. Tag styles and functionality don't load

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.3.16.1
- Craft version: 3.6.5.1
- Multi-site: No

**Additional context**
![Screen Shot 2021-02-12 at 12 37 19 pm](https://user-images.githubusercontent.com/21274925/107722594-30875c80-6d2f-11eb-9241-03432b1a52ff.png)
![Screen Shot 2021-02-12 at 12 36 59 pm](https://user-images.githubusercontent.com/21274925/107722599-341ae380-6d2f-11eb-98b8-23412776e7e5.png)

**Comment by engram-design** [comment]
Should be fixed in [1.3.17](https://github.com/verbb/formie/releases/tag/1.3.17)

**Comment by d-karstens** [comment]
Thanks @engram-design, unfortunately this issue is still happening.

Looks like `tags.js` just isn't called when the tag field isn't first

**Comment by engram-design** [comment]
Should be fixed this time for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.17",
  "...": "..."
}
```

Then run `composer update`.

**Comment by d-karstens** [comment]
Thank you!

**Comment by engram-design** [comment]
Fixed in [1.3.18](https://github.com/verbb/formie/releases/tag/1.3.18)
