### ISSUE TITLE
Field hidden using a conditional rule is still submitted after being reset

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#504]
**Description**
When a conditional rule is showing up a field, the field is displayed, completed, and finally the conditional field is modified again, the value of the field which is again hidden based on the conditional rule keeps it value.

That means that for example if going forward or back in a multi-pages form, a field which is hidden will retains its value whereas its value should be cleared as the field is hidden.

This should not be the expected behaviour. The field value should be empty if reset based on a conditional.

**Steps to reproduce**
1. Setup a multi-pages form
2. Setup a few fields, where one is hidden / shown based on a conditional rule
3. Fill in a new submission on front-end, using `craft.formie.renderForm`
4. Show an hidden field based on a conditional rule
5. Hide again this field based on a conditional rule
6. Submit the form and check the submitted values

**Additional info**
Plugin version: 1.4.7
Craft version: 3.6.17
Multi-site: No

**Comment by engram-design** [comment]
Hmmm, I'm ever so slightly on the fence about this one. For the most part, it would be a pain to lose this data if the user toggles whatever conditional you have multiple times.

For example, say you have a "Use billing address as shipping address" radio, and you've setup the usual address/city/state/etc fields to be conditionally hidden if this is "off". The user might fill in all billing information, then decide they want to toggle "on" which would wipe the fields, but toggling "off" would mean they start afresh.

If anything my proposed change would be to set all fields that are conditionally hidden to `null` only when the form is submitted, rather than anything client-side, to prevent the above scenario. I'm always just careful when dealing with wiping user-provided data.

**Comment by romainpoirier** [comment]
Yes, I was thinking about that way, only on the server-side. I thought this was not working as expected, and that conditional field which would be completed then hidden and submitted would be saved, but after a reduced case it may not be the case.

I think the only downside I got was while editing an already submitted form which is showing up prefilled: that way, the hidden field would maybe not be emptied if the condition to show it are not filled.

**Comment by engram-design** [comment]
That raises a good point editing the submission in the control panel. When conditionally hiding/showing fields that are also required, the front-end JS handles un-requiring hidden fields. Otherwise, it'd validate visually hidden fields and be unable to proceed.

We'd need similar functionality on the control panel when editing a submission. I wouldn't want the actual fields visually hidden in the control panel, just so everything is clear and visible to content editors.

Will give it some further thought.

**Comment by romainpoirier** [comment]
> the front-end JS handles un-requiring hidden fields

So to summarize, in the context of editing an existing submission on front-end, it should also emptying hidden required fields on server side (after submit).

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.7",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.4.8](https://github.com/verbb/formie/releases/tag/1.4.8)

**Comment by romainpoirier** [comment]
I still experience issue on this, with this setup:
1. I have some fields inside a _Group_ field ;
2. This _Group_ field is only show when the previous field, which is an _Agree_ field, is checked ;
3. On a multi-page forms, if I complete the fields in the _Group_, submit, then go back to this page, uncheck the _Agree_ field: the content of every Group fields is not cleared and still submitted (while they are hidden) ;

**Comment by engram-design** [comment]
Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.4.10](https://github.com/verbb/formie/releases/tag/1.4.10)
