### ISSUE TITLE
Adding a page condition doesn't hide the page tab

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#509]
**Description**
After setting up a page condition based on a field content, the conditional page tab is still showing up and accessible using the default `craft.formie.renderForm()` template method.

That's right that if the field condition on the current page does not match the rule, the page with the condition is skipped and the next one is displayed.
But that does not prevent showing up the tab, which can still be clicked.

I don't think this is the expected behaviour, mostly using the page reload (server-side) submission method.

Like for conditional fields, we would need to hide / show based on current form completion. This is currently not possible for the pages tabs using the same kind of conditions.

**Steps to reproduce**
1. Create a test form with 3 pages
2. Add a Single-line Text field on each page
3. Enable condition on the 2nd page, to show it if the Single-line Text field on the 1st page is `123`
4. Preview the form (using `craft.formie.renderForm()` method)
5. The 2nd page tab is not hidden, even if it is skipped if the the Single-line Text field on the 1st page is not `123`
6. The same result happens if the conditional is reversed: hide the 2nd page if the Single-line Text field on the 1st page **contains nothing** or **is not** `123`

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
Plugin version: 1.4.7
Craft version: 3.6.17
Multi-site: No

**Comment by romainpoirier** [comment]
**Additional informations**
Despite this in the documentation:
> When toggling fields, pages and buttons, Formie will add (or remove) a data-conditionally-hidden data attribute on respective elements. Through this, you’re free to alter the specifics of the hiding behaviour if required.
> In addition, any field that is required, but hidden through your conditions will be marked as un-required, as a hidden field cannot be required, as it’s impossible for a user to fill it out. This prevents validation issues for invisible fields.

Unfortunately, there are no `data-conditionally-hidden` attributes injected in the default template.

**Comment by engram-design** [comment]
Pretty sure this is just the **page tab** that isn't hidden - a clear oversight. The page itself should be hidden (so clicking next would skip the back, same for when going back), so long as the condition is met.

**Comment by romainpoirier** [comment]
With page reload as submission method, even if the tab that should be hidden is showing up, I still can click on it and display the page that should be hidden. This page is showing up.

In my reduced test case, I'm only showing this page if the only field on the first page has `123` as value. If `123` is submitted, it's going on this hidden setup page after submit. If something else is submitting, it's going to the next page after the one which is hidden. But in both cases, the page is not hidden and still accessible from the pages nav (with `Display Page Tabs` enabled).

**Comment by engram-design** [comment]
That's correct, the tab will show up and the page _technically_ accessible (because the tab gives you access). Like I said, clearly an oversight not checking this working with tabs.

**Comment by romainpoirier** [comment]
Sorry, I'm still not sure of what you ask or are planning to handle for that point.

As seen on the Formie documentation:
> When toggling fields, pages and buttons, Formie will add (or remove) a data-conditionally-hidden data attribute on respective elements.

But after checking the source code, this `data-conditionally-hidden` feature is only added on fields, not on page or their nav tabs.

Like the `getConditionalTestResult` function, would it be possible to give access to a such method to be able to hide or at least label which page should be hidden?

Currently we can retrieve the conditions rules using `page.settings.pageConditions`, but this output JSON which can't be interpreted. And there're no JS script to toggle it like it is for fields thanks to `verbb/formie/src/web/assets/frontend/src/js/fields/conditions.js`.

Why didn't you add a such method for the pages like you did for the fields? Are you planning to do so?

**Comment by engram-design** [comment]
> Why didn't you add a such method for the pages like you did for the fields? Are you planning to do so?

Because pages are different, and skipping pages is determined by the controller when hitting "next" and submitting a page. Yes, I'll ensure I fix this issue.

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.7",
  "...": "..."
}
```

Then run `composer update`.

**Comment by romainpoirier** [comment]
Thank you! But unfortunately I still don't see the `conditionally-hidden` attribute while inspecting the page, of course after updating to the early fix and trying in a reduced test case. I both tried to show / hide page based on the content of the first page field.

**Comment by engram-design** [comment]
Are you using custom templates? Do note [this change](https://github.com/verbb/formie/commit/6434adaf085565906f7986ad782e9bdecda1e62c#diff-3306c454a993841ede24889322d129f7f3709604c6e2a9c1e0709683f703b831).

Do you see `data-field-conditions` on the `data-tab` element? 
<img width="994" alt="Screen Shot 2021-07-01 at 7 01 42 pm" src="https://user-images.githubusercontent.com/1221575/124097318-cf261700-da9e-11eb-925b-9ba4407a3974.png">

There's no need to add the `data-conditionally-hidden` attribute on the page `.fui-page` elements - if that's what you mean?

**Comment by romainpoirier** [comment]
Yes for a currently useless reason I was using custom templates, which where in fact just a copy of the official ones.
I have now disabled this setting, and now can see the `data-field-conditions` attribute on the `data-fui-page-tab` element.

But that's all, the `data-conditionally-hidden` attribute is still not there, so it's hard to interpret the `data-field-conditions` value. When and how to show or hide that page based on this JSON data? This is showing how the rules works, but not what should be the current state.

**Comment by engram-design** [comment]
Anything with a `data-field-conditions` attribute will have the rules evaluated, and toggle a `data-conditionally-hidden` attribute on them, if it evaluates to true.

A quick demo of it in action: https://d.pr/v/FaZl3r

Any insight into your setup that might be different to mine?

**Comment by romainpoirier** [comment]
I made another reduced test case and I can confirm that is works. I will update later if I find any bug in a complex case. Thank you!

**Comment by romainpoirier** [comment]
Ok, I finally found another simple case when the `data-conditionally-hidden` attribute doesn't appears, where it I think it should:

1. Create a multi-pages form, for example with 3 pages ;
2. Add a _Single-line Text_ on the first page ;
3. Add another _Single-line Text_ field on each next pages ;
4. Add a conditional rule on the 2nd page, to show if all rules match:  _Single-line Text_ on the first page is `123` ;
5. Show the form using `craft.formie.renderForm()` ;
6. Inspect the 2nd page tab: it never get the `data-conditionally-hidden` attribute ;

**Comment by engram-design** [comment]
You're totally right. Fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by romainpoirier** [comment]
I can see no change using `dev-craft-3 as 1.4.8`. Isn't it as `1.4.9` instead of `1.4.8`?

**Comment by engram-design** [comment]
My apologies, I forgot I pushed a release yesterday. It should be `1.4.9`.

**Comment by engram-design** [comment]
Fixed in [1.4.10](https://github.com/verbb/formie/releases/tag/1.4.10)

**Comment by romainpoirier** [comment]
Unfortunately, I still see no change using `1.4.10`. The hidden page tab is still hidden when it is active. It keeps the `data-conditionally-hidden="true"` attribute when this page is showing.

**Comment by engram-design** [comment]
Is this related to your other issue https://github.com/verbb/formie/issues/521 where the conditions are set on a field from another page, with Page Reload as the action?

**Comment by romainpoirier** [comment]
Yes this ticket is for a bug under _Page Reload_ as the action. Except here it is on a page (tab) instead on a field.

On keypress, the tab is shown / hidden where visiting another page. But when redirected to this page, so when it's active, it remains hidden where it should not.

So yep, you could merge it to #521. Sorry for the duplicate!
