### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#60]
I was looking for a way to translate my forms. Things like placeholders, error messages, etc.
The way I did it with Sprout and is working now also is just using my own templates to overwrite the default ones and adding `|t` everywhere.

Eg. `placeholder: field.placeholder` from `single-line-text.html` would become `placeholder: field.placeholder|t`.

However, it seems this is something that could be added to the default templates to enable translations with the Craft translation files? I always found this to be a burden to have to do this manually all the time, especially since it is easily broken after plugin updates.

But maybe there is a good reason why this has not been added?

**Comment by engram-design** [comment]
Is there any reason to translate content? For instance, if you want the placeholder text in a certain language, then could you not input it as that content initially?

For instance, in your example - what happens when you change the value of the placeholder. You then need to update your translation to match. I'll admit though, there's probably not another way to manage a multi-lingual form though.

I'll give it some thought. At first glance, I don't see an immediate harm with doing this, if it's an easy-win. Otherwise, we end up going down the route of each field setting needs to be translatable, which is a much bigger task.

**Comment by TomDeSmet** [comment]
Form translations are always a pickle of course.
It seems my `|t` option is already giving me problems in the `_label.html` template.

But your proposed way means that on a multi-lingual site, you'd need to make copies of the same form.
That is a lot easier with Formie than it is with Sprout, I admit :)

I cannot think of any other solution right now.
Just dreaming out loud here: have synced fields with translatable labels, placeholders and error messages. :)

**Comment by AndrewMac** [comment]
I will certainly vote for this as well, if it's worth anything. 

If you've ever worked on a multilingual site, even though Craft is much better than anything else I've seen, you still take whatever small wins you can get, and things like this often do go into files in the translation folder. Yes, you do have to update the file if something changes, and a fully translatable module would be absolutely fantastic, but the translation file certainly does its job.

I ended up with the translation file (freeform.php) below, for instance, on a Thai-language site using Freeform (which does add the |t filter to its templates where necessary—see https://docs.solspace.com/craft/freeform/v3/setup/translating.html):

return array (
	'ask us a question' => 'ติดต่อสอบถาม',
	'email' => 'อีเมล',
	'fax' => 'แฟกซ์',
	'first name' => 'ชื่อ',
	'forms' => 'แบบฟอร์มต่างๆ',
	'last name' => 'นามสกุล',
	'location' => 'ที่ตั้ง',
	'mobile' => 'โทรศัพท์มือถือ',
	'name' => 'ชื่อ',
	'phone' => 'โทรศัพท์',
	'photo' => 'รูปภาพ',
	'question' => 'คำถาม',
	'search' => 'ค้นหา',
	'send question' => 'ส่งคำถาม',
	'subject' => 'หัวข้อ',
	'There was an error submitting this form' => 'เกิดข้อผิดพลาดในการส่งแบบฟอร์มนี้',
);

**Comment by engram-design** [comment]
@AndrewMac We're prepped all available string in English (of which there are a **lot**) here - https://github.com/verbb/formie/blob/craft-3/src/translations/en/formie.php, it's more the fact for multi-sites, the properties of the field and form itself aren't run through the translator. 

The thinking behind this was this if you was if you wanted a field label to be in German - you'd just enter it in German. This doesn't really fix the issue on a multi-site, where you might have "Company" being the field label in English, but want that to be "Unternehmen" for German. 

There's no good way to manage fields themselves being translatable in Craft. Formie's fields extend from Craft's own field system. The field's content themselves are of course multi-site enabled. It'd be nice to be able to switch site's for a form and edit everything about that per-site, but that's a massive undertaking.

But, this is all a separate topic about CP-based translations.

All the front-end labels, error messages, placeholders and just about any output I can find is now translatable in [1.2.3](https://github.com/verbb/formie/releases/tag/1.2.3). Follow the same steps as Craft's [Static Translations](https://docs.craftcms.com/v3/static-translations.html)

I'll also finish that once we've got some funds, we'll invest in https://crowdin.com/ (see https://github.com/verbb/formie/issues/62) for CP translations into other languages, but that doesn't really apply in your scenario. There's no way to translate field labels, placeholder, etc that are specific to your site and project.

**Comment by AndrewMac** [comment]
Thanks for adding those translation strings to the front-end! It's really great the way you've been adding so much to Formie so quickly. When I first saw it come out I wasn't able to leave Freeform, but after all the recent effort you've put in I think I'm ready to jump over to Formie. It would be great to switch to an Aussie developer!

**Comment by engram-design** [comment]
@AndrewMac No worries, and thanks for the comments! We certainly want to maintain the momentum with releases as well. The priority has always been to get feature parity with the other form plugins, and I think we're almost there. Of course, anything else you want/need feel free to send through.

Cheers!

**Comment by umkasanki** [comment]
Hi guys!
Could you please show the correct way to translate ajax error messages on a multilingual site? Maybe it is possible to pass translated messages from the template ..?
Thanks

**Comment by engram-design** [comment]
@umkasanki There are a couple of different ways. You can use [Static Translation](https://craftcms.com/docs/3.x/sites.html#static-message-translations) creating either a `site.php` file or a `formie.php` file.

Or you can [Override Form Settings](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-forms#override-form-settings) in your templates:

```
{% set form = craft.formie.forms.handle('contactForm').one() %}

{% do form.setSettings({
    errorMessage: 'Yo, you got an error!',
}) %}

{{ craft.formie.renderForm(form, options) }}
```

**Comment by umkasanki** [comment]
Thanks

**Comment by Timusan** [comment]
Two things I have noticed while trying to translate forms just now in relation to what is described above:

- The translation file 'formie.php' is not picked up, translations in the 'site.php' are working fine however. The `formie.php` file is placed in the site's `translations/nl/` (for Dutch translations) - the same location as the `site.php` main translations file. 
- Translating validation errors/error messages (such as the main `Couldn’t save submission due to errors.`) cannot be translated. Not statically (via `site.php` or `formie.php`) nor via the template (as described [here](https://verbb.io/craft-plugins/formie/docs/template-guides/rendering-forms#override-form-settings):).

This is tested on the latest dev as mentioned in #222 . Not ruling out that this is a problem between chair and keyboard 😉

**Comment by engram-design** [comment]
Hmmm, so as for the `formie.php` static translation override, I'm not quite sure what's going on there. We aren't doing anything special and are following the [Static Message Translations](https://craftcms.com/docs/3.x/sites.html#static-message-translations) guide. But it also depends on what you're translating. Front-end strings should be overridden using your `site.php` (so they can be site-specific), whilst Control Panel related strings should be in `formie.php`.

As for the error message, I can seemingly get this to work:
```
<?php

return [
    'Couldn’t save submission due to errors.' => 'Some override text.',
];
```

```
translations
    en
        site.php
```

![Screen Shot 2020-11-24 at 8 48 03 am](https://user-images.githubusercontent.com/1221575/100019251-d5ca1d00-2e31-11eb-9005-0cd43508a775.png)

**Comment by Timusan** [comment]
As for the difference between `formie.php` and `site.php`: Got it, I was talking about front-end strings (field labels, error messages) and it is clear that they should be put in the `site.php` file instead.

However, the error messages do not get translated. I neglected to say that I save the form using the form's AJAX capabilities instead of a page reload, but I guess this should not make any difference?

I tried switching the form to server-side submission to test however it keeps submitting via AJAX, even if I force the form via its settings during rendering time:

```
{% set form = craft.formie.forms.handle('formHandle').one() %}

{% do form.setSettings({submitMethod: 'page-reload'}) %}

{{ craft.formie.renderForm(form) }}
```

My apologies if I am spamming this closed ticket with potential new issues :sweat_smile: Just let me know if you rather have this in a new ticket instead.

**Comment by engram-design** [comment]
Ah yes, the Ajax message acts a littler differently. Should be fixed for the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.2.28",
  "...": "..."
}
```

Then run `composer update`.

As for the overrides, I can't replicate that. Can you try doing the following as a quick test, which should add a heading of the form name to the page:

```
{% do form.setSettings({submitMethod: 'page-reload', displayFormTitle: true}) %}
```

This should at least confirm if these overrides are being applied

**Comment by Timusan** [comment]
Yes, your latest fix in `dev` fixes the main error message, it can now be translated using static translation in `site.php`. Field error messages, however, still show up in English (eg. `This field is required.`), even though they are statically translated in the `site.php` file.

As for the form overrides, setting the `displayFormTitle` does display the form title, so that override is working. But setting `submitMethod` to `page-reload` does nothing - it still submits via AJAX.

**Comment by engram-design** [comment]
The field validations are the only real exception to what can be translated in the `site.php` file. In this instance, you'll need to put your translations in `formie.php`. Refer to https://github.com/verbb/formie/blob/craft-3/src/services/Rendering.php#L331-L358

This may change, but I need to consider if this will be a breaking change for people (I believe it will), as I don't want anyone's translations to be messed up.

I'm at a loss about the form overrides. Feel free to start a new issue about that one.

**Comment by Timusan** [comment]
Awesome, you are correct, putting the field validation messages in `formie.php` does the trick!

I'll look a bit more into those form overrides and if I cannot find anything I'll open a separate issue for that.
