### ISSUE TITLE
Server Error after updating Craft

### ISSUE THREAD

**Issue by AndrewMac** [verbb/formie#700]
**Description**
I started to get a Server Error when I updated to Craft 3.7.27 or 3.7.28 (they both came out really quickly).

It happens on the front-end and in some of the Formie pages in the control panel ("submissions" and the "edit form" screens). 

This is a screenshot of the error, and the stacktrace copied from Craft:

<img width="1382" alt="CleanShot 2022-01-06 at 18 55 44@2x" src="https://user-images.githubusercontent.com/70342/148348785-c832fea5-9504-42c6-a856-5c94252f18c0.png">

```
TypeError: Return value of craft\models\FieldLayout::getTabs() must be of the type array, null returned in /app/vendor/craftcms/cms/src/models/FieldLayout.php:258
Stack trace:
#0 /app/vendor/verbb/formie/src/models/FieldLayout.php(87): craft\models\FieldLayout->getTabs()
#1 /app/vendor/verbb/formie/src/elements/Form.php(587): verbb\formie\models\FieldLayout->getTabs()
#2 /app/vendor/verbb/formie/src/elements/Form.php(686): verbb\formie\elements\Form->getPages()
#3 /app/vendor/verbb/formie/src/elements/Form.php(1260): verbb\formie\elements\Form->hasMultiplePages()
#4 /app/vendor/verbb/formie/src/services/Rendering.php(90): verbb\formie\elements\Form->getFrontEndJsVariables()
#5 /app/vendor/verbb/formie/src/variables/Formie.php(103): verbb\formie\services\Rendering->renderForm(Object(verbb\formie\elements\Form), NULL)
#6 /app/vendor/twig/twig/src/Extension/CoreExtension.php(1564): verbb\formie\variables\Formie->renderForm('lannaQuestion')
#7 /app/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderForm', Array, 'method', false, false)
#8 /app/storage/runtime/compiled_templates/2b/2ba74c65d35c6108b9d70c25b42efe22830d2b3d5d2f629f3d05fb286660eb06.php(268): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderForm', Array, 'method')
#9 /app/vendor/twig/twig/src/Template.php(182): __TwigTemplate_4045189d211e66c355a2fab8faa28f0346d60640269033434b9b41504892ee72->block_content(Array, Array)
#10 /app/storage/runtime/compiled_templates/d4/d4f17c0083d5d0b761dc61eff296a53b0d5ad3d1fbc55ee79e7208fe5cda4717.php(278): Twig\Template->displayBlock('content', Array, Array)
#11 /app/vendor/twig/twig/src/Template.php(182): __TwigTemplate_274ce6f415f507c29396c5f3c67d82e3801d342451030f1dc782d735f3066394->block_siteLayout(Array, Array)
#12 /app/storage/runtime/compiled_templates/b4/b4275a1591755b5e6bcf21e2a6d8e8b8bcefad4e02068117449e420d1394b297.php(146): Twig\Template->displayBlock('siteLayout', Array, Array)
#13 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_17ea96e076d32b5463e48010d4c379d75a4051a70cc83527d2e9998d6fa5f4f5->doDisplay(Array, Array)
#14 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /app/storage/runtime/compiled_templates/d4/d4f17c0083d5d0b761dc61eff296a53b0d5ad3d1fbc55ee79e7208fe5cda4717.php(59): Twig\Template->display(Array, Array)
#16 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_274ce6f415f507c29396c5f3c67d82e3801d342451030f1dc782d735f3066394->doDisplay(Array, Array)
#17 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /app/storage/runtime/compiled_templates/2b/2ba74c65d35c6108b9d70c25b42efe22830d2b3d5d2f629f3d05fb286660eb06.php(56): Twig\Template->display(Array, Array)
#19 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_4045189d211e66c355a2fab8faa28f0346d60640269033434b9b41504892ee72->doDisplay(Array, Array)
#20 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /app/storage/runtime/compiled_templates/b3/b3e58f075a183d087c764e6b9ba008435bcb8e2a8d0ef9bd85c9cd3d4f1b33c0.php(50): Twig\Template->display(Array, Array)
#22 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c1341b1491bb8357036cad95aa2d3fa7b7203c786fb31c785e2901e4864c504a->doDisplay(Array, Array)
#23 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /app/storage/runtime/compiled_templates/f2/f2d5119075c1807e17cab337ab54ec78b73e25009929dec74b1d2823f1c6affb.php(43): Twig\Template->display(Array)
#25 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_bebd04d30792a939ae5f983ab37e6653147956c8ccee05fc9ef27e24e07e8511->doDisplay(Array, Array)
#26 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#28 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#29 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#30 /app/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_home', Array)
#31 /app/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('_home', Array)
#32 /app/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('_home', Array, 'site')
#33 /app/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('_home', Array)
#34 [internal function]: craft\controllers\TemplatesController->actionRender('_home', Array)
#35 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#36 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#37 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#38 /app/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('templates/rende...', Array)
#39 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#40 /app/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#41 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#42 /app/web/index.php(26): yii\base\Application->run()
#43 {main}
```

**Steps to reproduce**
1.
2.

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

**Additional info**
- Plugin version: 1.5.3
- Craft version: 3.7.28 Pro
- Multi-site: Yes

**Additional context**

**Comment by romainpoirier** [comment]
I can confirm that I get the same issue after updating from `3.7.27.1` to `3.7.28`.

**Comment by engram-design** [comment]
Can confirm this, looks like a Craft 3.7.28 issue - I'll chat with the Craft crew.

**Comment by benoitblancquaert** [comment]
I have the same issue with the latest version of Craft (3.7.28).

**Comment by engram-design** [comment]
Fixed in [1.5.4](https://github.com/verbb/formie/releases/tag/1.5.4)

**Comment by michaeldietiker** [comment]
@engram-design tested with Craft (3.7.28) and Formie (1.5.4).
Still getting an unknown property error: craft\models\FieldLayoutTab::settings

![Bildschirmfoto 2022-01-06 um 13 40 13](https://user-images.githubusercontent.com/44356685/148384405-9b88caff-a157-47e9-b798-089bcda50822.png)

Works with Craft (3.7.27.1) as expected.

**Comment by romainpoirier** [comment]
From my side, I don't get the error anymore in the CP (or can't replicate it at this time),   but I still get it on front-end.

**Comment by RyanRoberts** [comment]
@michaeldietiker Same here, different error though isn't it?

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.5.5](https://github.com/verbb/formie/releases/tag/1.5.5)
