### ISSUE TITLE
Errors with attachments on Freshdesk integration

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#725]
**Description**

Testing our integration with Freshdesk and running into errors when a Formie file upload field is mapped to the Attachments ticket field. 

When the form is submitted with the file upload field empty, it produces the error:
`Freshdesk: API error: “{"description":"Validation failed","errors":[{"field":"attachments","message":"It should not be blank as this is a mandatory field","code":"invalid_value"}]}”`

When the form is submitted with files selected in the file upload field, it produces the error:
`Freshdesk: API error: “{"description":"Validation failed","errors":[{"field":"attachments","message":"Value set is of type String.It should be a/an Array","code":"datatype_mismatch"}]}”`

**Steps to reproduce**
1. Create a form with a file upload field and map it to the Attachments ticket field for the Freshdesk integration.
2. Submit the form with upload field empty/filled.

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.7
- Craft version: Pro 3.7.30
- Multi-site: No

**Comment by jmauzyk** [comment]
On a related note, we have a custom ticket field in Freshdesk that is optional in the Formie form. When the field isn't filled out, the mapping returns a null value which results in the following error:

`Freshdesk: API error: “{"description":"Validation failed","errors":[{"field":"custom_fields.cf_order_number","message":"Value set is of type Null.It should be a/an String","code":"datatype_mismatch"}]}”`

Is it possible for the Freshdesk integration to leave optional ticket fields unset if the mapped value is null or otherwise empty?

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.7",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jmauzyk** [comment]
I was still having some issues with these sorts of errors so I dug into it a bit more. There are a few things at play. First, although`attachments` is defined as an optional field in the Freshdesk API, it seems that if the field is listed in the body, it becomes required. So when `attachments` is set, it has to have an array and that array cannot be empty. Second, their API requires that create/update requests with attachments have the `Content-Type` header set to `multipart/form-data`.

I've issued a pull request (#734) attempting to address both of these issues, though they required changing the visibility of a method or two. I've tested on my end and was able to successfully send payloads to Freshdesk both with and without attachments. I hope the PR is usable, let me know if I need to make any adjustments.

A third issue at play here seems to be related to the settings cache being removed from the integration object when a job fails. When retrying a job after the cache is stripped, `Integration::getFormSettings()` returns an empty array, which in turn causes `Integration::getFieldMappingValues()` to get mapped field values using empty `IntegrationField`s with no set type. This caused issues like the one I was seeing, in which retrying a failed `TriggerIntegration` job would result in an `attachments` field value of a comma-separated string of image URLs instead of an array.

**Comment by engram-design** [comment]
Yep, good pick up here. I'm not an expert on Freshdesk's API. However, attachments were certainly working for me when creating a ticket, so that seems odd - despite the API clearly stating that only multipart is supported. I believe it's because I was providing the URL to an already-uploaded asset in Craft, but now not so sure!

Let me double check that caching things to see if I can replicate that now.

**Comment by engram-design** [comment]
Fixed in [1.5.8](https://github.com/verbb/formie/releases/tag/1.5.8)
