### ISSUE TITLE
Mark as not spam doesn't work from CP edit submission page

### ISSUE THREAD

**Issue by jmauzyk** [verbb/formie#765]
**Description**
Trying to mark a submission as not spam from its CP edit page doesn't work.

**Steps to reproduce**
1. Go to the CP edit submission page for a spam submission.
2. Disable the **Mark as Spam** light switch and save.
3. Browser redirects to the submissions index, but the submission is still marked as spam.

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.9
- Craft version: Pro 3.7.33
- Multi-site: No

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.5.10](https://github.com/verbb/formie/releases/tag/1.5.10)

**Comment by jmauzyk** [comment]
@engram-design thanks for your work on this. Still having a slight issue related to this. I'm now able to mark a submission as not spam from its CP edit page, but when I do `isSpam` is set to `NULL` instead of `0`. As a result, when trying to manually run an integration or notification afterward I get an error: "Submission not found."

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.10",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.5.11](https://github.com/verbb/formie/releases/tag/1.5.11)
