### ISSUE TITLE
GQL form `submitActionUrl` not as expected

### ISSUE THREAD

**Issue by tremby** [verbb/formie#854]
**Description**

I expected `submitActionUrl` to be the URL I am supposed to submit the form contents to. In fact, it appears to somehow follow `redirectUrl`.

**Steps to reproduce**
1. Make a form. Leave configuration at default.
2. Query via GQL for its `submitActionUrl`. It comes back as the empty string, which seems like a bug.
3. Reconfigure the form; set its "action on submit" to "redirect to a URL". Fill in the URL as `http://example.com/redirection-target` or something
4. Query via GQL again -- see `http://example.com/redirection-target` come through both on `submitActionUrl` and `redirectUrl`.
5. Reconfigure the form; set "action on submit" back to "message".
6. Query via GQL again -- see `submitActionUrl` come through as `http://example.com/redirection-target`, and `redirectUrl` come back as the empty string. I would expect `null` rather than empty string as the redirect URL (though this is not a big deal), and I'd expect the submit action URL to be the URL I'm meant to submit the form to, not the out-of-date redirection target.

Incidentally, after I've configured the action to redirect to an entry, the details of that entry still come through on `redirectEntry` even when I've reconfigured it to just give a message or whatever. This is less harmful; I'm not going to open a ticket about it.

As far as I can tell, there's no way to get the URL I'm meant to post the form to. I would imagine that was supposed to be `submitActionUrl`.

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: either
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: craft-4 at ea113467
- Craft version: 4.0.x at 9d2c37d
- Multi-site: Yes

**Comment by tremby** [comment]
It dawns on me that I'm going to submit form responses via GraphQL and so I don't actually need a traditional API endpoint for the form submission. However:

- I would still expect `submitActionUrl` to be the place I can post a traditional form to, so I still think this issue is valid.
- I see from looking at the GQL schema that `save_testForm1_Submission` is the mutation I'm looking for for this particular form. I can probably rely on that format (`save_${formHandle}_Submission`) being stable (right?) so I can likely submit an arbitrary form without specific code for that form. I'd much prefer to cut out the guesswork, however, so it'd nice to be able to query for that mutation name. Perhaps a `submitMutationName` field?

**Comment by engram-design** [comment]
The endpoint to submit submissions to is static, and won't change. This will be `http://your-site.test/actions/formie/submissions/submit`, which follows the Craft controller endpoint structure. You may hit some issues with CORS, and a CSRF token, depending on how you send the payload to the server. For instance, you'll need to support a same-site cookie in order to validate the CSRF token. [Further reading](https://github.com/verbb/formie/issues/834).

So the `submitActionUrl` refers to the URL you set in your form settings, that should be the action on submit. I understand that's maybe awkwardly named in your context, but still applicable for headless scenarios. Here, you would want to check if this has a value, and redirect it on your front-end after submission. It's not a bug that it's empty unless you have the form settings set for that value. You should query for `submitAction` first and foremost to determine what you need to do on your front-end (show a message, redirect, etc). You can't just rely on "if there's a value for `submitActionUrl` then redirect the user to that URL.

I've got a docs page / user guide lined up after Craft 4's release on how to do a REST-based, headless submission rather than using GraphQL mutations (which already has a guide https://github.com/verbb/formie-headless).

And that's correct on the mutation front, that'll always be the format, as we need to provide the mutation context of _what_ form you're submitting a mutation on, in order to know what fields are available. But yes, happy to add that mutation name as a property in the Forms query if that'll help, which we do in a similar fashion or fields and their input name.

**Comment by engram-design** [comment]
Added `submissionMutationName` for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.0-beta.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
> The endpoint to submit submissions to is static, and won't change. This will be `http://your-site.test/actions/formie/submissions/submit`, which follows the Craft controller endpoint structure

Don't you think that should be available somewhere here? That's what I expected to find on `submitActionUrl` -- something to put in `<form action="here">`.

> So the `submitActionUrl` refers to the URL you set in your form settings, that should be the action on submit.

On the "behaviour" tab I can enter a URL if I change "action on submit" to "redirect to a URL", but then anything I put in the "redirect URL" box appears in both `submitActionUrl` *and* `redirectUrl`. So I still don't understand. If I then change to something like "reload page", the `redirectUrl` is now empty string, and the `submitActionUrl` is still the stale redirection URL I configured earlier. What is the point of `submitActionUrl` if it only ever has empty string or a redundant copy of `redirectUrl` or a stale value which used to be `redirectUrl` and which should not be used?

**Comment by tremby** [comment]
I just updated and now I have crashing errors. If I try to go to my form's edit page:

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'submitActionEntryId' in 'field list' in /srv/my-project/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT `id`, `n...')
#2 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /srv/my-project/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /srv/my-project/vendor/craftcms/cms/src/db/Query.php(153): yii\db\Query->all(NULL)
#5 /srv/my-project/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all()
#6 /srv/my-project/vendor/verbb/formie/src/services/Notifications.php(335): verbb\formie\services\Stencils->getAllStencils()
#7 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(539): verbb\formie\services\Notifications->getExistingNotifications(Object(verbb\formie\elements\Form))
#8 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(102): verbb\formie\controllers\FormsController->_prepareVariableArray(Array)
#9 [internal function]: verbb\formie\controllers\FormsController->actionEdit(172, NULL, NULL)
#10 /srv/my-project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /srv/my-project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /srv/my-project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#13 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('formie/forms/ed...', Array)
#14 /srv/my-project/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('formie/forms/ed...', Array)
#15 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#16 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /srv/my-project/web/index.php(12): yii\base\Application->run()
#18 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'submitActionEntryId' in 'field list'
The SQL being executed was: SELECT `id`, `name`, `handle`, `data`, `templateId`, `submitActionEntryId`, `defaultStatusId`, `dateDeleted`, `uid`
FROM `formie_stencils`
WHERE `dateDeleted` IS NULL
ORDER BY `name` in /srv/my-project/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT `id`, `n...')
#1 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT `id`, `n...')
#2 /srv/my-project/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /srv/my-project/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /srv/my-project/vendor/craftcms/cms/src/db/Query.php(153): yii\db\Query->all(NULL)
#5 /srv/my-project/vendor/verbb/formie/src/services/Stencils.php(65): craft\db\Query->all()
#6 /srv/my-project/vendor/verbb/formie/src/services/Notifications.php(335): verbb\formie\services\Stencils->getAllStencils()
#7 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(539): verbb\formie\services\Notifications->getExistingNotifications(Object(verbb\formie\elements\Form))
#8 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(102): verbb\formie\controllers\FormsController->_prepareVariableArray(Array)
#9 [internal function]: verbb\formie\controllers\FormsController->actionEdit(172, NULL, NULL)
#10 /srv/my-project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /srv/my-project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /srv/my-project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#13 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('formie/forms/ed...', Array)
#14 /srv/my-project/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('formie/forms/ed...', Array)
#15 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#16 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /srv/my-project/web/index.php(12): yii\base\Application->run()
#18 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'submitActionEntryId' in 'field list'
)
```

**Comment by engram-design** [comment]
> Don't you think that should be available somewhere here? That's what I expected to find on submitActionUrl -- something to put in `<form action="here">`.

Probably, yes! Added `submissionEndpoint` to the `FormInterface`.

> On the "behaviour" tab I can enter a URL if I change "action on submit" to "redirect to a URL", but then anything I put in the "redirect URL" box appears in both submitActionUrl and redirectUrl. So I still don't understand. If I then change to something like "reload page", the redirectUrl is now empty string, and the submitActionUrl is still the stale redirection URL I configured earlier. What is the point of submitActionUrl if it only ever has empty string or a redundant copy of redirectUrl or a stale value which used to be redirectUrl and which should not be used?

So typically, you'll always want to refer to `redirectUrl` to get where (if anywhere) to redirect after the form has been submitted. This will check if you:
- Are redirecting (to a URL or Entry)
- If an entry, return the URL of that entry
- If a static URL, then return that

So for a cover-all-bases approach, check:
- If `submitAction = "message"` then show the message
- If `submitAction = "reload"` then reload the page, easy enough
- Otherwise (or, if `submitAction = "url" || submitAction = "entry"`) redirect to the value in `redirectUrl`

But the individual pieces are there in case you want to mess around with that. You could obviously handle the last two steps individually using `submitActionUrl` for when `submitAction = "url"` and using `redirectEntry { url }` for when `submitAction = "entry"` but that's something we can simplify with a single `redirectUrl` property.

As for the stencil error, that should be brought across from `craft-3` now in the latest `craft-4` branch.

**Comment by tremby** [comment]
I'm still getting an error, though now it's a toast rather than a full screen crash. In the log:

```
2022-04-29 00:05:44 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized. {"memory":23929264} 
2022-04-29 00:05:44 [web.ERROR] [yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: verbb\formie\elements\Form::hasOverriddenTitle() in /srv/my-project/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /srv/my-project/vendor/craftcms/cms/src/base/Element.php(1951): yii\base\Component->__call('hasOverriddenTi...', Array)
#1 /srv/my-project/vendor/verbb/navigation/src/elements/Node.php(170): craft\base\Element->__call('hasOverriddenTi...', Array)
#2 [internal function]: verbb\navigation\elements\Node::getNodeElementTitleHtml(Object(craft\events\DefineElementInnerHtmlEvent))
#3 /srv/my-project/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DefineElementInnerHtmlEvent))
#4 /srv/my-project/vendor/craftcms/cms/src/helpers/Cp.php(446): yii\base\Event::trigger('craft\\helpers\\C...', 'defineElementIn...', Object(craft\events\DefineElementInnerHtmlEvent))
#5 /srv/my-project/vendor/craftcms/cms/src/web/View.php(2155): craft\helpers\Cp::elementHtml(Object(verbb\formie\elements\Form), 'index', 'small', NULL, false, true, true, true, false, false)
#6 /srv/my-project/vendor/craftcms/cms/src/web/View.php(1704): craft\web\View->_getCpElementHtml(Array, false)
#7 /srv/my-project/storage/runtime/compiled_templates/12/12526885f6ecba34639d1bf927aef812.php(38): craft\web\View->invokeHook('cp.elements.ele...', Array)
#8 /srv/my-project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8bdfa1e7053263a43293b283c8efd0bc->doDisplay(Array, Array)
#9 /srv/my-project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /srv/my-project/storage/runtime/compiled_templates/e3/e383631eed122cf906a2970f80b2f10b.php(155): Twig\Template->display(Array)
#11 /srv/my-project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_73f76d570fe158cd3622e0912a595e91->doDisplay(Array, Array)
#12 /srv/my-project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /srv/my-project/storage/runtime/compiled_templates/05/057a8dffc540b22cde38d65c619e42fe.php(127): Twig\Template->display(Array)
#14 /srv/my-project/vendor/twig/twig/src/Template.php(394): __TwigTemplate_538910f71e5f031a6d336485b4aca0c8->doDisplay(Array, Array)
#15 /srv/my-project/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /srv/my-project/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#17 /srv/my-project/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#18 /srv/my-project/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#19 /srv/my-project/vendor/craftcms/cms/src/web/View.php(414): Twig\Environment->render('_elements/table...', Array)
#20 /srv/my-project/vendor/craftcms/cms/src/base/Element.php(999): craft\web\View->renderTemplate('_elements/table...', Array)
#21 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(644): craft\base\Element::indexHtml(Object(verbb\formie\elements\db\FormQuery), Array, Array, '*', 'index', true, true)
#22 /srv/my-project/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(142): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#23 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#24 /srv/my-project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /srv/my-project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#26 /srv/my-project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('get-elements', Array)
#27 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('element-indexes...', Array)
#28 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('element-indexes...', Array)
#29 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#30 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 /srv/my-project/web/index.php(12): yii\base\Application->run()
#32 {main} {"memory":36028816,"exception":"[object] (yii\\base\\UnknownMethodException(code: 0): Calling unknown method: verbb\\formie\\elements\\Form::hasOverriddenTitle() at /srv/my-project/vendor/yiisoft/yii2/base/Component.php:300)"} 
```

**Comment by tremby** [comment]
Ah, I failed to mention that this new error is on the form listing page. I *can* get to a form edit page if I know its URL.

**Comment by engram-design** [comment]
Ah, looks like that's a brand-new error from Craft 4-RC2, related to the Navigation plugin. Looking into it.

**Comment by tremby** [comment]
Oh yeah, wow, I didn't even notice that in the stack trace!

**Comment by engram-design** [comment]
If you update to the latest `craft-4` branch for Navigation, that should fix that up.

**Comment by tremby** [comment]
I think maybe we're still not quite understanding each other.

> So for a cover-all-bases approach, check:
> 
> - If `submitAction = "message"` then show the message
> - If `submitAction = "reload"` then reload the page, easy enough
> - Otherwise (or, if `submitAction = "url" || submitAction = "entry"`) redirect to the value in `redirectUrl`
> 
> 
> But the individual pieces are there in case you want to mess around with that. You could obviously handle the last two steps individually using `submitActionUrl` for when `submitAction = "url"` and using `redirectEntry { url }` for when `submitAction = "entry"` but that's something we can simplify with a single `redirectUrl` property.

I still can't figure out what `submitActionUrl` is for.

Here are all the possible values I've found for `submitAction`:

- `url` -- We want to redirect to an arbitrary URL. In this case I get what I need from either `redirectUrl` or `submitActionUrl` -- when `submitAction` is `url` I have only ever seen exactly the same string in both of these fields. So `submitActionUrl` is redundant in this case.
- `entry` -- We want to redirect to an entry. I get what I need from either `redirectUrl` or `redirectEntry`. `submitActionUrl` has nothing useful, in fact it has a stale manually-entered URL for the redirection previously configured for the `url` setting, which will likely not lead to the right place. I'd call this harmful.
- `message` -- We just need to display a message, so no need to look at `redirectUrl` (empty string) and there's nothing useful in `submitActionUrl` (stale URL again)
- `reset` -- We just want to reset the form, so no need to look at `redirectUrl` (empty string) or `submitActionUrl` (stale URL again)
- `reload` -- We just want to reload the page, so no need to look at `redirectUrl` (empty string) or `submitActionUrl` (stale URL again)

So I don't see a single case where `submitActionUrl` gives anything useful, except for `url` but in that case exactly the same string is available on `redirectUrl`.

**Comment by engram-design** [comment]
We're in agreement on that point. The `submitActionUrl` performs the same function as `redirectUrl`. Sure you can get the value `submitActionUrl` which the the URL you've set in the control panel, even if the submit action is set to show a message - you'll still get the saved setting.

So as I mentioned, you don't need `submitActionUrl`, just use `redirectUrl`. I _might_ consider removing it, but _maybe_ some people might like to have the setting available even if the behaviour is not to redirect to a URL. But maybe we just steer people towards convention.

I also understand the point about the stale URL setting. It's debatable whether this should be removed if you switch behaviour types.

**Comment by tremby** [comment]
OK. I can't think of any reason anyone would want to get at that URL in those cases, so my vote if I had one would definitely be for removing it to eliminate a source of confusion. I mean, it lead to this whole ticket. :laughing:

**Comment by engram-design** [comment]
Now's the time for breaking changes! Removed `submitActionUrl`.
