### ISSUE TITLE
Pre populate doesn't work with phone number field

### ISSUE THREAD

**Issue by parthi-me** [verbb/formie#969]
**Description**
I tried to update the phone number field from the query parameters. But it doesn't work as expected. But other input fields were working fine with pre-populated query values. Also, the default value also not working.

**Steps to reproduce**
1. Add a phone number field 
2. Disable country dropdown option
2. Set the default value for the field
3. Set pre-populate query param name in settings tab

### Form settings
- Multi-page form: No
- Submission Method: Ajax 
- Client-side Validation: Yes 
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.6.2
- Craft version: 3.7.45.2
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Fixed in [1.6.3](https://github.com/verbb/formie/releases/tag/1.6.3)

**Comment by parthi-me** [comment]
@engram-design Default value is still not working with the phone field. But I can confirm that the pre-populate from the query string is working as expected with the latest release.

**Comment by DenyEs** [comment]
I have the same issue with default value not being passed in for 'Phone Number' field when the form renders in Craft 4 - 4.8.7 and Formie - 2.1.9

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.1.9"`.

**Comment by DenyEs** [comment]
Cheers Josh, tested it and it works!

**Comment by engram-design** [comment]
Fixed in [2.1.10](https://github.com/verbb/formie/releases/tag/2.1.10)
