### ISSUE TITLE
Access Agree field settings

### ISSUE THREAD

**Issue by urani** [verbb/formie#988]
### Question

I have an Agree button within the form and i want to be able to access the Description. 

Agree button has a handle: privacyStatementAgreement 

{% do form.setFieldSettings('privacyStatementAgreement', {
    
    description: 'Message',
}) %}

But once i do this, the description disappears. 
Any suggestion on how to achieve this? 

Thanks

**Comment by engram-design** [comment]
Yeah that's tricky because the `description` setting for the field expects it to be a ProseMirror schema (what we use for rich text), not just HTML, and it'll try and convert that to HTML. I've now added `descriptionHtml` for you to set.

Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.1",
  "...": "..."
}
```

Then run `composer update`.  Update your code to:
```
{% do form.setFieldSettings('privacyStatementAgreement', {
    descriptionHtml: 'Message',
}) %}
```

**Comment by urani** [comment]
Thanks for your quick reply. 
I tried updating via composer, but first it asked me to upgrade to php 8 and now its requires me to update to Craft 4. 
Is there someway to skip this update? 

Thanks

**Comment by engram-design** [comment]
You didn't specify which version you were on, so I assumed you were on the latest Formie 2, but sounds like you're on Formie 1 for Craft 3. At the moment, this change will only be available for Formie 2/Craft 4.

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/formie/releases/tag/2.0.2)

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/formie/releases/tag/2.0.2)

**Comment by giorgiopogliani** [comment]
@engram-design this is still happening on the formie `1.6.14`

**Comment by giorgiopogliani** [comment]
@engram-design could we backport the fix? thanks

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.14",
  "...": "..."
}
```

Then run `composer update`.

**Comment by giorgiopogliani** [comment]
Now I'm getting: `verbb\formie\fields\formfields\Agree::getDescriptionHtml(): Return value must be of type verbb\formie\fields\formfields\Markup, Twig\Markup returned`

This is the twig code I was using: 
```twig
{% do form.setFieldSettings('privacy', {
  descriptionHtml: "I accept the {terms}."|t(params = {
    terms: privacy.privacyPolicy.getLink(),
  })
}) %}
```

**Comment by engram-design** [comment]
Sorry, did just notice that. Try another `composer update`.
